### ISSUE TITLE
Fit Error: validation_step() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by yuyonod** [williamFalcon/pytorch-lightning#105]
### Common bugs:
Hello, I installed pytorch lightning like
pip install git+https://github.com/williamFalcon/pytorch-lightning.git@master --upgrade
(btw, i couldnt install by pip install pytorch_lightning: i got error related to setuptools even i have setuptools)

then run following scripts which described in 'How do I use it'
I got an error at section 2 (Fit with a trainer) 
**Describe the bug**
`trainer.fit(model)`
>> validation_step() takes 3 positional arguments but 4 were given

**Environment:**
 - OS: Ubuntu 18.04
 - Python: 3.6.8
 - Anaconda: 1.7.2
 - torch: 1.2.0
 - torchvision: 0.4.0
 - pytorch_lightning: 0.4.4

I'm sorry that I'm not fluent English speaker and hope we'll get figure it out.

**Comment by thomasw21** [comment]
The README.md isn't up to date. If you look at the documentation, you need to use the following signature

```python
def validation_step(self, batch, batch_nb, dataloader_nb):
```

**Comment by williamFalcon** [comment]
that's weird.  did you try to install in the conda env?

```bash
conda create --name my_env python=3.6    

act my_env    

conda install pytorch==1.2.0 torchvision -c pytorch

pip install pytorch-lightning
```

**Comment by williamFalcon** [comment]
@thomasw21 just noticed the readme didn't match the latest release. it's been updated. good catch!

**Comment by williamFalcon** [comment]
@yuyonod will reopen if you can't get the install to work!

**Comment by williamFalcon** [comment]
In 0.4.5 dataloader_nb is not necessary if you're using a single validation dataset
