### ISSUE TITLE
Choice of Logging Backend

### ISSUE THREAD

**Issue by awaelchli** [williamFalcon/pytorch-lightning#111]
**Is your feature request related to a problem? Please describe.**
Currently only logging to TensorBoard is supported, but there are many other great logging tools out there (Visdom, W&B, MLflow).

**Describe the solution you'd like**
There should be a way for the researcher to choose a logging backend and/or a way to implement/override a custom logger given the interface Lightning requires. 

**Describe alternatives you've considered**
Force everyone to use TensorBoard :(

**Additional context**
Since the Experiment is a subclass of SummaryWriter, it cannot be changed easily. It would require a lot of refactoring.

**Comment by williamFalcon** [comment]
duplicate #47

**Comment by awaelchli** [comment]
Stupid of me, how did I not see the other issue... Thanks for taking a look at this.

**Comment by williamFalcon** [comment]
all good!!

**Comment by williamFalcon** [comment]
@awaelchli want to try implementing this support? (using the other issue)

**Comment by awaelchli** [comment]
@williamFalcon I would like to try it this weekend. I only discovered lightning recently and I am not yet familiar with the details of this library.
