### ISSUE TITLE
Support of different batch types

### ISSUE THREAD

**Issue by c00k1ez** [williamFalcon/pytorch-lightning#113]
Hi!
As I say later, I got two problems: 
-  in my research I have to put to model three tensors, like 
`{'tokens': torch.Tensor, 'head': torch.Tensor, 'tail': torch.Tensor}`, but when I tried to use GPU to train it, I had error `RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'`.
And its easy to fix (for single GPU, I do not know how to work with DDP and DP), just add two conditions.
- Second problem about GPU too. In my dataloader I have batch like dict with tokens. I use pretrained embeddings, so I can vectorize my batch only in `training_step` or `validation_step`, but I cannot push it in GPU memory, so I have same error  `RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'`.

**Comment by williamFalcon** [comment]
can you paste your code here?

**Comment by c00k1ez** [comment]
What code exactly do you need? This is my model methods https://pastebin.com/xL8T8svQ

**Comment by williamFalcon** [comment]
just return:
```python   
    return {'loss': loss, 'tokens': texts['tokens'], ...}
```

**Comment by c00k1ez** [comment]
but error raise in `scores = self.forward(texts)`

**Comment by williamFalcon** [comment]
there's no code there... 
```python   
def forward(self, batch):
    # batch shape [batch_size, seq_len, embedding_dim]
    # batch - dict('tokens': tokens[batch_size, seq_len, embedding_dim],
    #              'head': head[batch_size, seq_len, char_pad_len,],
    #              'tail': tail[batch_size, seq_len, char_pad_len,]
    #             )
    tokens, head, tail = batch['tokens'], batch['head'], batch['tail']    
    ...
```

**Comment by williamFalcon** [comment]
also, your batch is whatever you decide in the dataloader... can you post that code too?

it'd be easier to debug if you post your full LightningModule code.

**Comment by c00k1ez** [comment]
Ok, this is all my module code (https://pastebin.com/a9PK2z95). Error throws in 37 line.
And this is dataset code (https://pastebin.com/VADi8hcn). 

As I understand, in `training_step` and `validation_step` I have to compute loss from each data_batch. But I cannot do this, because I cannot push my vectorized batch to GPU
