### ISSUE TITLE
Errata in the readme?

### ISSUE THREAD

**Issue by Lezcano** [williamFalcon/pytorch-lightning#117]
In the `MNIST` example in the readme, the functions `tng_dataloader`, `val_dataloader`, and `test_dataloader` return the same object. I think that at least for test, the `train` flag used to create the `MNIST` object should be `False`. I am not aware of how to extract automatically a validation dataset from the `MNIST` dataloader in torch.

**Comment by williamFalcon** [comment]
nah, it’s just for illustration and simplicity only. mnist has no val set. in the real world you’d split the train portion into a train/val split by subclassing the mnist dataset. 

the readme is to illustrate the main ideas
