### ISSUE TITLE
Fix appveyor build

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#122]
windows support is not a priority. If the badge can be fixed today we'll keep appveyor. Otherwise we'll drop it from the project.

@Borda

**Comment by Borda** [comment]
it failed because we were installing 1.1.0 directly but in `requirements.txt` is now required 1.2.0
Seems that the fix is 
```
pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
```
just testing in a local branch and I will create PR if it solves the issue...

**Comment by Borda** [comment]
@williamFalcon you may use "Assignees" instead of simply mentioning next time... :)

**Comment by williamFalcon** [comment]
i tried. it doesn’t let me assign people...

**Comment by Borda** [comment]
@williamFalcon you still shall update the badge to point to your project so it is automatically updated according to your actual status, not my fork... see https://github.com/williamFalcon/pytorch-lightning/pull/123#issuecomment-521679440
https://github.com/williamFalcon/pytorch-lightning/blame/master/README.md#L13

**Comment by williamFalcon** [comment]
@borda. something weird happening with the build on 3.6

**Comment by Borda** [comment]
@williamFalcon could you pass me a link to the build so I may have look?
