### ISSUE TITLE
early stopping or checkpointing without val step

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#126]
**Is your feature request related to a problem? Please describe.**
When val step isn't defined, early stopping nor checkpointing work. 

**Describe the solution you'd like**
Early stopping should look at training_step metrics instead

**Comment by williamFalcon** [comment]
any takers?

**Comment by GuHongyang** [comment]
Hi, I want a try?

**Comment by GuHongyang** [comment]
Hi, I want a try?
