### ISSUE TITLE
Propose to open a discussion group for general discussions

### ISSUE THREAD

**Issue by Ir1d** [williamFalcon/pytorch-lightning#134]
**Is your feature request related to a problem? Please describe.**

I think it might be a good idea to have a discussion group on IM for general discussions.

**Describe the solution you'd like**

I dont know, Discord, Telegram perhaps? some of my own projects are maintained with discussions on these platforms, and they seem equally good to me.

**Describe alternatives you've considered**

Or maybe slack or gitter :)

**Comment by williamFalcon** [comment]
@lr1d great suggestion!   

https://gitter.im/PyTorch-Lightning/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
