### ISSUE TITLE
Progress bar code simplification.

### ISSUE THREAD

**Issue by sebftw** [williamFalcon/pytorch-lightning#146]
**Is your feature request related to a problem? Please describe.**
I think some of the code for the progress bar could be simplified.
The main issue is that the code is a little harder to read and maintain, so it is not a huge issue.

We have `self.prog_bar` which is the tqdm bar, and `self.progress_bar` which is the boolean value, which tells whether this bar should be enabled. Some examples of use in the code:

[Line 444](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L444):
```
if self.progress_bar and self.prog_bar is not None:
    self.prog_bar.update(1)
```
If `self.progress_bar` is False, then why would self.prog_bar not be None?

[Line 649](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L649):
```
# show progbar only on prog_rank 0
self.prog_bar = self.prog_bar and self.node_rank == 0 and gpu_nb == 0
```
In this line self.prog_bar takes on a boolean value. But that is what `self.progress_bar` was mean to be.

**Describe the solution you'd like**
I think a solution would be to adopt the style that `self.prog_bar` should be None in case it is not enabled. It should then also be renamed to `self.progress_bar` (Like in https://github.com/williamFalcon/pytorch-lightning/issues/119), such that we have only one variable instead of two.

I am not sure if this may mess with some of the distributed training code though.

**Additional context**
I think maybe the intention is that you should be able to toggle the progress bar between calls to `trainer.fit`. If this is a functionality we would like to retain, maybe progress_bar should be an argument to the `trainer.fit` call instead. So instead of having a trainer object with the `self.progress_bar` state, it may be more fitting to have it as part of the model fitting, which is an "atomic" function that blocks the program for a while.
The added benefit is that the number of arguments in `Trainer.__init__` would be reduced.

**Comment by sebftw** [comment]
A similar issue is with [line 808](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L808):
```
# update LR schedulers
if self.lr_schedulers is not None:
    for lr_scheduler in self.lr_schedulers:
        lr_scheduler.step()
```
It could be changed to 
```
for lr_scheduler in self.lr_schedulers:
        lr_scheduler.step()
```
Likewise i'd like to maybe adopt the style that lists and dataloaders/iterables never be None if possible - unless we want to signal something specifically.
The reason is that this way we can always rely on the invariant that e.g. `for lr_scheduler in self.lr_schedulers` is a no-op(eration) if it is empty, so we wont have to check [`if self.val_dataloader is not None`](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L360) etc.
I am from a Java background, where this is "considered harmful", because you can frequently run into NullPointerExceptions, so Empty lists is the norm.

Any thoughts?

**Comment by williamFalcon** [comment]
@sebftw took care of progress bar. want to do a separate PR for self. lr_schedulers = [] always?

**Comment by williamFalcon** [comment]
@sebftw we'll keep the flag in the trainer. don't want to start spreading out where flags go. easier to look in one place for capabilities

**Comment by sebftw** [comment]
@williamFalcon Thanks. I agree. I'll make a PR for the lists and some refactoring. It might conflict with https://github.com/williamFalcon/pytorch-lightning/pull/165 so I'll wait till it's merged.

**Comment by williamFalcon** [comment]
@sebftw merged
