### ISSUE TITLE
We need more detailed comments.

### ISSUE THREAD

**Issue by lartpang** [williamFalcon/pytorch-lightning#164]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I do not know the meaning of the parameter. We need more detailed comments, otherwise it is not convenient for developers.

like these code:

https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L86-L115

**Describe the solution you'd like**

Like PyTorch, every function and every parameter, they all have corresponding comments.

**Describe alternatives you've considered**

More frequent search in documents. :tired_face: 

**Additional context**

![image](https://user-images.githubusercontent.com/26847524/63580150-c3c25480-c5c6-11e9-8d6f-c10b1fc6af52.png)

I use the PyCharm, I am used to using `ctrl-q` to view function documentation... So I think this requirement is very important, and certainly other users have considered similar issues.

**Comment by williamFalcon** [comment]
@lartpang good suggestion. will document functions inline

**Comment by williamFalcon** [comment]
@lartpang this was merged a bit ago. Please check to make sure it's what you meant
