### ISSUE TITLE
Add .load function for more flexible loading

### ISSUE THREAD

**Issue by IvanLazarevsky** [williamFalcon/pytorch-lightning#183]
**Is your feature request related to a problem? Please describe.**
I'm using Lightning for a few hours, so maybe I am missing something. pl.LightningModule's tng_dataloader and similar methods couple DataLoaders to the module. Ok, I can pass them as the constructor arguments, but then methods like MyModule.load_from_metrics will not work.

**Describe the solution you'd like**
Option to pass DataLoaders to Trainer or Trainer.fit instead of specifying them in the LigthningModule.

**Describe alternatives you've considered**
Make it possible to pass additional arguments to load_from_metrics and other methods, which create a specified LightningModule instance.

**Comment by williamFalcon** [comment]
you wouldn’t pass them as constructor arguments. why would you want to do that?

can u post your code?

**Comment by williamFalcon** [comment]
@ivanlazarevsky this make sense? closing the ticket. i’m renaming this ticket to implement the load function discussed

**Comment by IvanLazarevsky** [comment]
> @IvanLazarevsky this make sense? closing the ticket. i’m renaming this ticket to implement the load function discussed

Yes, thanks.
