### ISSUE TITLE
issue about version number

### ISSUE THREAD

**Issue by hubutui** [williamFalcon/pytorch-lightning#187]
Hey, it seems that the release/tag number is messed up. The lastest one shoule be `0.4.8`, but you used `0.11 0.111 0.112 0.113 0.12 0.121 0.122 0.13 0.13.0 0.21`, and `0.122 > 0.48`, `0.122` is regarded as the latest release/tag. Consider bump version to `1.0`?

**Comment by williamFalcon** [comment]
that’s weird. tag should be 0.4.8 must have been a typo

**Comment by hubutui** [comment]
yeah, I'm trying to create package for ArchLinux automatically, and the package bot check version and found the latest release is 0.121. I have to ignore these version to get the right version.

**Comment by williamFalcon** [comment]
that’s weird. latest release is 0.4.8. latest tag is also 0.4.8. maybe the pypi version is the one?

**Comment by hubutui** [comment]
I check PyPI release history, https://pypi.org/project/pytorch-lightning/#history, seems all right. I could also check version number from PyPI instead of GitHub repo.

**Comment by williamFalcon** [comment]
fixed
