### ISSUE TITLE
AttributeError: 'Experiment' object has no attribute 'get_meta_copy'

### ISSUE THREAD

**Issue by PeterouZh** [williamFalcon/pytorch-lightning#19]
https://github.com/williamFalcon/pytorch-lightning/blob/b8c7baa8acce9e363c33d2580eb1abcca322a211/pytorch_lightning/models/trainer.py#L419
I encountered this problem when I used ddp.

**Comment by williamFalcon** [comment]
upgrade to the new version and try again?

**Comment by williamFalcon** [comment]
does it work now?

**Comment by williamFalcon** [comment]
closing for now. Please reopen if the problem persists!
