### ISSUE TITLE
Thanks for sharing!

### ISSUE THREAD

**Issue by fighting41love** [williamFalcon/pytorch-lightning#2]
Good repo! Thanks for sharing!

**Comment by williamFalcon** [comment]
Thanks! Let me know how it can be improved!

**Comment by williamFalcon** [comment]
Hi! lighting has been updated to include: tensorboard visualization, multi-gpu training, multi-node training, thoroughly documented and updated clean syntax. 

Would be auper helpful if you tried version 0.21 and provided feedback!

Thanks!

**Comment by lkhphuc** [comment]
It looks super nice, I will try it on a kaggle competition and see how it goes.

**Comment by williamFalcon** [comment]
@lkhphuc go for it! post how you do here!
