### ISSUE TITLE
How to get current LR within lightningModule

### ISSUE THREAD

**Issue by shoarora** [williamFalcon/pytorch-lightning#212]
I'd like to log LR throughout the training process in tensorboard.  
As I understand it, that's as simple as adding it to `update_tng_log_metrics` function or directly adding metrics to test_tube.Experiment.

But I can't find where to get the optimizer/scheduler info from within the lightningModule.  How could I access this information?

**Comment by williamFalcon** [comment]
self.trainer.lr_schedulers

**Comment by bparaj** [comment]
For pytorch-lightning version `1.9.0`, I am getting this error:

```
AttributeError: 'Trainer' object has no attribute 'lr_schedulers'
```

**Comment by Serious-H** [comment]
Me too. Have you solved it @bparaj

**Comment by bparaj** [comment]
Assume I have `configure_optimizers()` defined as:

```python3
    def configure_optimizers(*args, **kwargs):
        optimizer = torch.optim.Adam(model.parameters(), **config["optimizer"])
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, gamma=0.95, step_size=5)
        return [optimizer], [lr_scheduler]
```

I then used the following to access the last learning rate:

```python3
lr = trainer.lr_scheduler_configs[0].scheduler.get_last_lr()[0]
```
