### ISSUE TITLE
add test description 

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#216]
to test do:
trainer =...
trainer.test(model) 

or fit and test

**Comment by expectopatronum** [comment]
Where is that?

**Comment by williamFalcon** [comment]
It’s not in the docs. Need to give examples of how to use.

**Comment by awaelchli** [comment]
I think this can be closed @williamFalcon. Test description is [here].(https://williamfalcon.github.io/pytorch-lightning/Trainer/Testing%20loop/)
