### ISSUE TITLE
ERROR: No matching distribution found for pytorch-lightning

### ISSUE THREAD

**Issue by lironghua318** [williamFalcon/pytorch-lightning#220]
pip install  pytorch-lightning 
ERROR: No matching distribution found for pytorch-lightning

**Comment by williamFalcon** [comment]
please describe you os, conda version, etc... we test for installing lightning, so this is likely misconfiguration of your device somehow

**Comment by enod** [comment]
I've replicated this error by installing pytorch-lightning via pip on nvidia jetson nano. 

Is it expected not to work on ARM? I've successfully install pytorch 1.3 on nano.
