### ISSUE TITLE
Integration with knockknock

### ISSUE THREAD

**Issue by heytitle** [williamFalcon/pytorch-lightning#227]
**Is your feature request related to a problem? Please describe.**
Training usually takes time. It would be more efficient to let it run and do something else, then and come back when it's done.

**Describe the solution you'd like**
Preferably, we would like to have a process that automatically informs us when the process finishes. Fortunately, there is a package, called [Knockknock][knock], that we can integrate into pytorch-lightning and it will take care how to send notification to us through our favourite channels, i.e. Slack. 

If you're interested, I can take a look on how to implement the feature.

[knock]: https://github.com/huggingface/knockknock

**Comment by williamFalcon** [comment]
great suggestion. go for it! @thomwolf

**Comment by Ir1d** [comment]
we can also consider https://github.com/notifiers/notifiers which works well with https://github.com/Delgan/loguru
