### ISSUE TITLE
How to save model name with my own variable?

### ISSUE THREAD

**Issue by gravitychen** [williamFalcon/pytorch-lightning#229]
comments claim that 
"""Save the model after every epoch.
    `filepath` can contain named formatting options,
    which will be filled the value of `epoch` and
    keys in `logs` (passed in `on_epoch_end`).

But how to set the keys in logs, and how to operate  on_epoch_end, can you make some examples?

thank you so much

**Comment by williamFalcon** [comment]
sorry, could you elaborate on what you are trying to do? to use on epoch end do:

```
class MyModel(LightningModule):

    def on_epoch_end():
        # do something
```

**Comment by gravitychen** [comment]
> sorry, could you elaborate on what you are trying to do? to use on epoch end do:
> 
> ```
> class MyModel(LightningModule):
> 
>     def on_epoch_end(self):
>         # do something
> ```

oh I just want to save the accuracy number  on my model name. just like 
there is a "ckpt" directory which contains all of models
and my models' name are like below:  
acc_0.1_epoch_1.pth
acc_0.2_epoch_2.pth
acc_0.3_epoch_3.pth
acc_0.4_epoch_4.pth
acc_0.5_epoch_5.pth

But I have no idea how to make this happen

**Comment by williamFalcon** [comment]
There is currently no way to do that. However, if that's important to you and you want to add a feature, you could add it to the Checkpoint callback as an argument.

```
CheckpointCallback(..., prefix='your_str')
```

**Comment by williamFalcon** [comment]
Updated docs here:
https://pytorch-lightning.readthedocs.io/en/latest/Trainer/Checkpointing/
