### ISSUE TITLE
When running single_gpu_node_dp_template.pj, missing 'dp' or 'ddp' param

### ISSUE THREAD

**Issue by TheStoneMX** [williamFalcon/pytorch-lightning#235]
### Common bugs:
1. When running single_gpu_node_dp_template.pj, missing 'dp' or 'ddp' param   
2. PyTorch 1.1.0 vs 1.2.0 support [see FAQ](https://github.com/williamFalcon/pytorch-lightning#faq)    

**Describe the bug**
When running single_gpu_node_dp_template.pj, missing 'dp' or 'ddp' param.

**To Reproduce**
1. Run sample py file with a GPU or GPUs machine
2. error :  When using multiple GPUs set Trainer(distributed_backend=dp) (or ddp)

**Expected behavior**
we should have one more argument in the gpu args

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Visual Code
 - Version 1.38.1

**Additional context**

**Comment by TheStoneMX** [comment]
fiexed issue by adding 
 parent_parser.add_argument('--dist_bak_end', type=str, default='dp',help='When using multiple GPUs set Trainer(distributed_backend=dp) (or ddp)')

    trainer = Trainer(experiment=exp,checkpoint_callback=checkpoint,early_stop_callback=early_stop,gpus=hparams.gpus,distributed_backend=hparams.dist_bak_end,)

**Comment by williamFalcon** [comment]
@TheStoneMX thanks for the fixes!

**Comment by TheStoneMX** [comment]
> @TheStoneMX thanks for the fixes!

Hey, I really like your lightning API, will keep working with it and if I find anything else I will help you, me...

**Comment by williamFalcon** [comment]
Awesome! welcome to the lightning community!

**Comment by TheStoneMX** [comment]
> Awesome! welcome to the lightning community!

Thanks! I am learning the framework, I am trying to use it in some of my past kaggle competitions, to practice, and benchmark it, if I have questions where should I post them? or write to you directly?

**Comment by williamFalcon** [comment]
gitter or here

**Comment by TheStoneMX** [comment]
great ! I just test you over gitter

**Comment by TheStoneMX** [comment]
@williamFalcon,

I have been looking at it, and I was wondering how will you use it with transfer learning? leaving the top off and or activating or deactivating some of the layers of the pre-trained model.
