### ISSUE TITLE
Training on a single specific GPU

### ISSUE THREAD

**Issue by Colanim** [williamFalcon/pytorch-lightning#239]
**Is your feature request related to a problem? Please describe.**
I can't run my training on 1 single GPU, where I choose the GPU. Running the trainer with :

`Trainer(gpus='3')` gives :

> RuntimeError: CUDA error: invalid device ordinal

**Describe the solution you'd like**
When a single GPU ID is given, training run on that specific GPU

**Describe alternatives you've considered**
We have to set CUDA_VISIBLE_DEVICES=3 and run with `Trainer(gpus=1)`

**Comment by williamFalcon** [comment]
Trainer(gpus=[3])

**Comment by Colanim** [comment]
`Trainer(gpus=[3])`

gives me :

> RuntimeError: CUDA error: invalid device ordinal

**Comment by Colanim** [comment]
It worked when I do :

`export CUDA_VISIBLE_DEVICES=0,1,2,3`

before running the trainer.

I have no idea why though...
