### ISSUE TITLE
how to setup slurm in a cluster

### ISSUE THREAD

**Issue by shuxp** [williamFalcon/pytorch-lightning#25]
This is a great repo of warper pytorch when using ddp, especially using slurm, which has little repos. I found slurm in mmdetection also. 

In my group, we have 3 nodes, each of them has 4 GPUs.
I want to setup a slurm cluster to fully use these nodes. But little data can be found. 
So could you please share some toturial of setup up slurm in a cluster? My nodes are all ubuntu 18.04 server.

**Comment by williamFalcon** [comment]
Glad you found it useful! I'll put a SLURM tutorial together tomorrow.
In the meantime, check out the multi-node example:

https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/examples/new_project_templates/multi_node_cluster_template.py

**Comment by shuxp** [comment]
Thanks. Looking forward to see SLURM tutorial.

**Comment by williamFalcon** [comment]
https://link.medium.com/Bs6NxJyjRY

**Comment by williamFalcon** [comment]
Closing this because the tutorial has been created :)

But, feel free to add a comment if the tutorial is missing something or needs clarification.

**Comment by shuxp** [comment]
> Closing this because the tutorial has been created :)
> 
> But, feel free to add a comment if the tutorial is missing something or needs clarification.

In the blog, there is a comment: 

```Disclaimer: This tutorial assumes your cluster is managed by SLURM.```

In fact, I have no idea about how to manage cluster using slurm...

When cluster is managed by slurm, I can try PTL in my cluster.

**Comment by williamFalcon** [comment]
SLURM is installed by your cluster administrator. I guess here I’m using cluster to refer to an academic or corporate cluster. 

If it’s literally your own cluster with your own machines then PTL may not support that case because it uses NCCL to communicate and a few flags SLURM sets. 

But if it’s an academic or corporate cluster, it most likely has SLURM installed. 

If you use srun or sbatch to run jobs, then you’re using SLURM.

**Comment by shuxp** [comment]
Yes, now I want to try slurm by myself...

**Comment by illcat** [comment]
I feel SLURM is not convenient for Horovod.
