### ISSUE TITLE
Error while importing pytorch_lightning

### ISSUE THREAD

**Issue by IISCAditayTripathi** [williamFalcon/pytorch-lightning#259]
### Common bugs:
1. Tensorboard not showing in Jupyter-notebook see [issue 79](https://github.com/williamFalcon/pytorch-lightning/issues/79).    
2. PyTorch 1.1.0 vs 1.2.0 support [see FAQ](https://github.com/williamFalcon/pytorch-lightning#faq)    

**Describe the bug**
I am getting the following bug while importing pytorch_lightning
![Bug](https://user-images.githubusercontent.com/42270643/65712498-ce37a880-e0b4-11e9-9f6b-a2286a161116.PNG)

**To Reproduce**
1. Open terminal
2. type "python3"
3. type "import pytorch_lightning" and press "Enter"

**Desktop (please complete the following information):**
 - CUDA 10.1 
 - python 3.7

**Comment by williamFalcon** [comment]
looks like you're not in your cuda environment
