### ISSUE TITLE
Add tensorboard logger

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#265]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by williamFalcon** [comment]
@neggert i think you mentioned adding this at some point. tagged you to track this issue

**Comment by yassersouri** [comment]
What kind of functionality do you expect for the tensorbaord logger?

**Comment by williamFalcon** [comment]
everything listed in the summarywriter. but we that for free. this PR of for a wrapper on that logger (see mlflow or testtube logger)

**Comment by tshrjn** [comment]
Also, a way to do custom logging, perhaps by getting access to SummaryWriter at end of each forward pass?

**Comment by williamFalcon** [comment]
you can use self.logger from anywhere to do whatever you want. check out the gan demo

**Comment by Borda** [comment]
@williamFalcon could you please update description of this ticket or at least remove the template text... Thx

**Comment by williamFalcon** [comment]
@Borda @yassersouri anyone interested in implementing this?

This would be a new logger using strictly summarywriter under the hood from PyTorch.
