### ISSUE TITLE
'LightningTemplateModel' object has no attribute '_lazy_train_dataloader'

### ISSUE THREAD

**Issue by chuong98** [williamFalcon/pytorch-lightning#266]
**Describe the bug**
Try to run the file single_gpu_node_ddp_template.py, to test the code, but got error:

**To Reproduce**
1. Download folder pytorch-lightning/examples/new_project_templates/
2. run file: $python ingle_gpu_node_ddp_template.py$
3. See error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu18
 - pytorch 1.2, cudatoolkit  9.2 
 - pytorch_lgihting 0.5

![Screenshot from 2019-09-29 14-44-13](https://user-images.githubusercontent.com/15174756/65828677-a704f500-e2c7-11e9-8b3a-707672cf866b.png)

**Comment by yoyololicon** [comment]
https://github.com/williamFalcon/pytorch-lightning/blob/324c28eb5e0e3c472d2a6afe2400c55049b1ab78/examples/new_project_templates/lightning_module_template.py#L211

Change function name from 'train_loader' to 'tng_loader' can fix it.

**Comment by williamFalcon** [comment]
tng changed to train in 0.50

**Comment by chuong98** [comment]
Thanks. Changing the name to train_loader solve the problem. Also, my dataset returns a dict before. I change it to return a tuple, so now I can use ddp option.
