### ISSUE TITLE
How to use EarlyStopping and ModelCheckpoint

### ISSUE THREAD

**Issue by hrukalive** [williamFalcon/pytorch-lightning#267]
The `logs` passed into the `on_epoch_end` method of both ModelCheckpoint and EarlyStopping seems to have the `loss` field set to a string, which leads to exception when comparing with the last best result. Following codes in trainer.py,
```
 407     @property
 408     def __training_tqdm_dict(self):
 409         tqdm_dict = {
 410             'loss': '{0:.3f}'.format(self.avg_loss),
 411             'epoch': '{}'.format(self.current_epoch),
 412             'batch_nb': '{}'.format(self.batch_nb),
 413         }
```
How should I use the ModelCheckpoint and EarlyStopping, is adding my own field in `progress` field when returning from `training_step` the way to go? What is the purpose of converting to string?

#### What's your environment?   
- conda version (no venv)   4.7.12
- PyTorch version   1.2.0
- Lightning version   0.5.0
- Test-tube version  0.7.1

**Comment by williamFalcon** [comment]
tqdm_dict is strictly for logging. To use early stopping or checkpointing:

1. tell the checkpoint what you want to monitor (ie: ```your_acc_or_something```).
2. In training_step return something like:
```
return {'loss':some_loss, progress:{'your_acc_or_something': someValue}}
```
