### ISSUE TITLE
Streamlined UX in saving, loading, continue training.

### ISSUE THREAD

**Issue by lkhphuc** [williamFalcon/pytorch-lightning#27]
Currently each time I ran the command with the same experiment name, a new version is created and trained from scratch.
If I wanted to load back the model to continue training, I have to create a different script, input the path for the previous checkpoints and meta_tags.

Proposal:
- Start training, input only 1 `log_path` and 1 `experiment_name`. Test_tube data and saved models will be included in the same folder.
- In each experiment, default is to create a new model and trained from scratch (current behavior)
- If user passed in `--continue-training`, model will load the latest model (not necessarily the best model) from the latest version, then create a new experiment version and continue training from there.
- If user passed in `--continue-training--best`, model will load the the best model from the latest version, then create a new experiment version and continue training from there.
- If user passed in `--continue-training(--best) --version=X`, auto load the model from version X and start training.

In the end, all the path and dir are determined from only the log_path and name of experiment, and default behavior is the same as of now: 
`python train.py --exp_name=exp1 --....`
If user want to change some hyperparams, or start finetuning, they will only need to add:
`python train.py --exp_name=exp1 --....  --continue-trainig--best --version=x`

What do you think?
Happy to discuss more, as I am not sure this is suitable for cluster training or not.
I can make a PR if you're interest.

**Comment by williamFalcon** [comment]
Great suggestion. Let's address each point first.

1. Test-tube logs and weights can't be forced to be in the same path. A user might have a restriction to save weights and logs to different folder. This could be for disk space or for ease of SCP files.

2. With that said, continue training can still work. It's actually already supported but meant for cluster training only. However, I agree it's a good idea to change the signatures and docs a bit to ALSO allow this for non-cluster training.

To do that here are the things that need to be changed:
1. Update the [save function](https://github.com/williamFalcon/pytorch-lightning/blob/b88307e927e5240f711ab199dc81054e65965f67/pytorch_lightning/root_module/model_saving.py#L54) to behave like this [hpc_save function](https://github.com/williamFalcon/pytorch-lightning/blob/b88307e927e5240f711ab199dc81054e65965f67/pytorch_lightning/root_module/model_saving.py#L150-L175) (which saves training state as well).   
2. Delete the hpc_save function.
3. Register the new save fx [here](https://github.com/williamFalcon/pytorch-lightning/blob/b88307e927e5240f711ab199dc81054e65965f67/pytorch_lightning/root_module/model_saving.py#L106) (for cluster tng).
4. Change the signature of [hpc_load](https://github.com/williamFalcon/pytorch-lightning/blob/b88307e927e5240f711ab199dc81054e65965f67/pytorch_lightning/root_module/model_saving.py#L177).   
5. Register the new hpc_save in the same fx as (3).   
6. This is where it gets tricky. It might be easier to give the trainer either a new flag or a function like restore_training. Not sure which one might be a better UX. 

At the end of the day, we want hpc_save/load and non-hpc_save/load to now behave the same.

Thoughts?

@cinjon any suggestions?

**Comment by lkhphuc** [comment]
Great. I will start reading the hpc code as I didn't use DDP before and try making some changes.

**Comment by williamFalcon** [comment]
ok, so, let’s do it where if the test tube version is the same then it continues training?

so, nothing of the external api needs to change, just internal + docs

**Comment by williamFalcon** [comment]
@lkhphuc how's it going? Did you take a look at the hpc method signatures?

**Comment by lkhphuc** [comment]
Sorry, I've been busy the last few days. I will spend some time on it in the next week.
Around the API for this change, I think:
- Everytime you run an experiment, the version of that experiment is bumped (current behavior).
- If additional argument `--load-model=best/latest`, the best/latest checkpoint from the *latest* version is loaded back.
- If additional arguments `--load-model=best/latest --from-version=X`, the best/latest checkpoint from version *X* is loaded back.
- If additional argument `--from-version=X`: the *latest* checkpoint from version *X* is loaded.

Together, I will introduce two new arguments in Trainer, the default will behave like current, combine they can load checkpoint best/latest  from version latest/X.

How do you think?
Should `--load-model=best/latest/X` with X is arbitrary epoch number?

**Comment by williamFalcon** [comment]
No worries. I think we're saying the same thing but in different ways haha.

I don't think we need to add any more arguments. The only change to the public API that needs to be made is to load the latest weights whenever the exp version is specified.

Case 1: No exp version given. Version is bumped (current behavior)

Case 2: Exp version is given. Then exp continues where it left off (this is already the current behavior). The only addition here is  that it should load the latest weights available for that version.

Case 2 covers the 3 flags you mentioned, so there's no need to add any more arguments, just change the internal loading (ie: look for the latest checkpoint at the beginning of training. If the version is new there won't be any, if it's an old version, the user had to have set that on purpose. and thus would be expected to load the latest weights).
