### ISSUE TITLE
New logger abstraction breaks self.experiment

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#279]
with the new abstraction we can't do:
```python
self.experiment.log_histogram(...)
```

instead we have to do:
```python
self.experiment.experiment.log_histogram(...)
```  

@neggert any suggestions on how to fix? Ideally the user can just access the self.experiment object directly and operate on it.

**Comment by neggert** [comment]
I might be missing something, but can't you do `self.logger.experiment.log_histogram(...)`. AFAIK, `self.experiment` doesn't exist anymore.

We could certainly add a `log_histogram` method to the base logger and just not implement it for loggers that don't support it.

**Comment by williamFalcon** [comment]
it's all good. it's just weird to have to do self.logger.experiment instead of self.logger

**Comment by williamFalcon** [comment]
#304 has the clean docs
