### ISSUE TITLE
Switch from print to logging

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#282]
Use logging instead of print.   (@Ir1d you brought this up before)

Suggested by @adefazio

**Comment by Borda** [comment]
I think that we were talking about it already a few months back :]

**Comment by Ir1d** [comment]
I suppose f-strings are preferred?
should we exposure logger as an option, since I prefer loguru, while others might like something else.

**Comment by Ir1d** [comment]
Given a second thought, what about adding a `info` and some `debug` function into LightningLoggerBase?
Something like: `self.logger.info()` , and users will be free to use whatever logger they like by specifying in [custom logger](https://williamfalcon.github.io/pytorch-lightning/Trainer/Logging/#custom-logger).
I can bring a PR for this.

**Comment by williamFalcon** [comment]
Please use f-strings!

**Comment by humandotlearning** [comment]
okay as @williamFalcon suggested i'll go with f-string. I have done a performance comparison if anyone is interested. 
https://colab.research.google.com/drive/1J6-SFq5nDGTYDH7GIpzixbjYS0UvZ30E

**Comment by Borda** [comment]
@humandotlearning @lr1d already started in #457

**Comment by Ir1d** [comment]
actually I'm stuck with how to let users select custom printing function? Any idea on this?

**Comment by Borda** [comment]
@Ir1d what do you mean by custom printing function? `logging.info/debug/warning` / `print()`... ?

**Comment by Ir1d** [comment]
@Borda I mean using other libraries such as [loguru](https://github.com/Delgan/loguru). But yes, what if someone wants to use debug/warning or other stuffs

**Comment by Borda** [comment]
it is nice library, but I would follow the same strategy as for PyTorch, do not include anything extra until it is really needed so I would sta just with the standard `logging`

**Comment by Borda** [comment]
@williamFalcon @Ir1d just noticed that using f-string makes unable to use python 3.5 and lower...
https://www.reddit.com/r/Python/comments/5xswh9/can_you_import_fstrings_in_python_35/
https://stackoverflow.com/questions/55182209/f-string-invalid-syntax-in-python-3-5

**Comment by Ir1d** [comment]
@Borda Yes, and I believe @williamFalcon is aware of this fact :joy:

**Comment by ethanjperez** [comment]
It's possible to use [f2format](https://pypi.org/project/f2format/) to convert f-strings to str.format, to be compatible with Python <=3.5

**Comment by williamFalcon** [comment]
@ethanjperez amazing haha. it’s finally happening :)

i think it’s a good place to start for a PR @ethanjperez ?

**Comment by Borda** [comment]
@ethanjperez very nice!

**Comment by Borda** [comment]
@ethanjperez it is true, but I am not sure that we do not want to have this `"".format()` formatting...
it works exactly as it is written in the package description:
```python
# the original code
var = f'foo{(1+2)*3:>5}bar{"a", "b"!r}boo'
# after `f2format`
var = 'foo{:>5}bar{!r}boo'.format((1+2)*3, ("a", "b"))
```
@williamFalcon ^^
