### ISSUE TITLE
Validation_end outputs should be auto logged to logger

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#283]
Currently, output of validation_end end up nowhere. We should log them to tf automatically.

Suggestion by @adefazio

**Comment by neggert** [comment]
I think right now they get added to `tqdm_dict`, then they end up getting logged during the next training epoch. This means that one epoch's validation metrics end up getting logged many times, which is kind of annoying. I think maybe we should decouple external logging from tqdm.

Things to log:
* During training epoch, every `row_log_interval`, log loss and anything in 'prog' dictionary returned by `training_step`.
* After validation, log values returned by `validation_end`

Anything else?

**Comment by williamFalcon** [comment]
Fixed in #307
