### ISSUE TITLE
Modify param printing to show top level modules only

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#284]
Add a model summary option that just shows the number of parameters for the top level modules. 

- Set pd.options.display.float_format = ’{:,}’.for- mat so it uses comma separators.
- Also summarize the number of parameters like 1,000,234 to 1M.
- use 1k, 1M, 1B, 1T, etc...

Suggested by @adefazio

Specifically, change:
```python
Trainer(print_weights_summary=True)
```   

To:
```python
# default
Trainer(weights_summary='full')

# second option
Trainer(weights_summary='top')
```

**Comment by awaelchli** [comment]
I would like to do this.
Regarding the parameter printing: 
Do you prefer `39M` or `39 M` (with space)
Here are two example outputs:
Option 1 (spacing):
```
        Name         Type Params    In_sizes   Out_sizes
0       c_d1       Linear   39 M    [5, 784]  [5, 50000]
1    c_d1_bn  BatchNorm1d  100 K  [5, 50000]  [5, 50000]
2  c_d1_drop      Dropout    0    [5, 50000]  [5, 50000]
3       c_d2       Linear  500 K  [5, 50000]     [5, 10]

```
Option 2 (no spacing)
```
        Name         Type Params    In_sizes   Out_sizes
0       c_d1       Linear    39M    [5, 784]  [5, 50000]
1    c_d1_bn  BatchNorm1d   100K  [5, 50000]  [5, 50000]
2  c_d1_drop      Dropout      0  [5, 50000]  [5, 50000]
3       c_d2       Linear   500K  [5, 50000]     [5, 10]
```

Also, what do we print after trillion? Perhaps we can stop abbreviating and continue with comma separation:  `100T`, `10,000T`, `1,000,000T` etc. 
I know it's unrealistic to have so many params but let's anyway handle these edge cases.

**Comment by williamFalcon** [comment]
awesome! 
1. spaces
2. good idea for trillion
