### ISSUE TITLE
GPU memory show max/min only

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#289]
Instead of logging GPU mem for all GPUs, probably better to just show the min/max usage? Maybe the flag can be modified?

```python
# now
Trainer(log_gpu_memory=False)  

# proposed
Trainer(log_gpu_memory='min_max')  

# and for all GPUs
Trainer(log_gpu_memory='all')  

```

@adefazio

**Comment by vhsw** [comment]
Should it be by default `min_max` or empty string or `False`?

**Comment by williamFalcon** [comment]
default = None
