### ISSUE TITLE
Pass experiment tags to MLFlowLogger

### ISSUE THREAD

**Issue by festeh** [williamFalcon/pytorch-lightning#297]
**Is your feature request related to a problem? Please describe.**
When using MLFlowLogger, I'm unable to easily set experiment tags, like username or run name.

**Describe the solution you'd like**
Add parameter `tags=None` which is passed to `MLFlowLogger`. Tags will be passed to `create_run` method

**Describe alternatives you've considered**
Manually hack logger, get experiment from it and set tag there

If you don't see any drawbacks, I can make a PR

**Comment by neggert** [comment]
Sounds like a great idea. Want to take a stab at a PR?
