### ISSUE TITLE
Using multiple loggers

### ISSUE THREAD

**Issue by ceyzaguirre4** [williamFalcon/pytorch-lightning#317]
**Describe the solution you'd like**
Trainer could receive a list of loggers instead of only one, all loggers would be called at the appropriate times.

**Describe alternatives you've considered**
Alternatively could create a customLogger that logged the information to all relevant destinations (eg. tensorboard AND mlflow)

**Comment by neggert** [comment]
What about using the existing base logger to create a composite logger that takes a list of loggers and calls them all?

**Comment by williamFalcon** [comment]
Would it be helpful to add an example of this to the docs?
