### ISSUE TITLE
Missing metrics on Tensorboard

### ISSUE THREAD

**Issue by rcmalli** [williamFalcon/pytorch-lightning#324]
**Describe the bug**
Validation metrics don't show up on Tensorboard.

**To Reproduce**
1. `pip install -U pytorch-lightning`
2. run example from examples/basic_examples with `python cpu_template.py`
3. Open Tensorboard 
4. Only epoch number appears at the scalars page.

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by williamFalcon** [comment]
update to latest version

**Comment by rcmalli** [comment]
I am already using pytorch-lightning version 0.5.1.3

**Comment by williamFalcon** [comment]
got it. just updated the demo. try again?

**Comment by rcmalli** [comment]
Yes, the problem still continues. It is even worse now since the dictionary has repeated keys at [here](https://github.com/williamFalcon/pytorch-lightning/blob/46b55d9aaa494773301be67af41a1b8bebf55960/examples/basic_examples/lightning_module_template.py#L102).

The missing part is the metrics are not published to Tensorboard. Both `loss` and the other validation metrics.

**Comment by williamFalcon** [comment]
only the things in progress_bar get plotted

**Comment by williamFalcon** [comment]
fixed. try again?

**Comment by rcmalli** [comment]
Yes, it is fixed.
