### ISSUE TITLE
Logger fails at scale

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#342]
Didn't happen before, but now this is happening:

When running on 1 or 2 nodes the logger works fine.
When running on 2+ nodes nothing logs... 

Might be a race condition which dist.barrier() might fix.

@neggert any thoughts?

**Comment by jamesjjcondon** [comment]
I can't get anything to log other than epoch and gpu details, even with single GPU. Is this coming from trainer.trainer around _process_output()? If someone can point me in the right direction, maybe add in some prints() or extra error messages, I might be able to submit a PR.

**Comment by williamFalcon** [comment]
ok, fixed the issue. I was still referencing the logger.experiment object outside of the trainer. This shouldn't be done in any way.

@jamesjjcondon verify with this fix?

**Comment by jamesjjcondon** [comment]
Yep. working now. Cheers. And I just saw your 9-steps medium article from July. Super helpful. Thanks!
