### ISSUE TITLE
Stablize api, provide backward compatibility and deprecation warning

### ISSUE THREAD

**Issue by tamyiuchau** [williamFalcon/pytorch-lightning#344]
Hi,

Pytorch Lightning is great and I enjoy the Keras-like standard training routine with the highly customizable pytorch experience. 

I do plan to move most of my pytorch models training to PyTorch-lightning but the rapid release this weeks broke my code several time, and maintaining multiple version on different environments is such a headache.

I do appreciate the move to a better api interface ie tng_dataloader vs training_dataloader.
However, I do think it is necessary to provide backward compatibility between minor version update. 

I would like to create a pull-request to provide the polyfilling code and corresponding deprecation warning.  The list of changes I observed in these few days are

1.  - [x] tng_dataloader -> training_dataloader

2. - [x] experiment-> logger

Is there any more things that i can add to the list?

**Comment by williamFalcon** [comment]
Great idea! Version 5.0 should have been the last major API change. The minor releases where to fix critical bugs around logging, and the new ddp2.

You can find all those changes in #119

**Comment by tamyiuchau** [comment]
Implemented.
