### ISSUE TITLE
No way to disable checkpoint callback

### ISSUE THREAD

**Issue by neggert** [williamFalcon/pytorch-lightning#346]
With the recent change to provide a checkpoint callback by default, there's no way to disable checkpointing. Passing `checkpoint_callback=None` results in the default checkpointer being created.

In `Trainer.__Init__`:

```python
        self.checkpoint_callback = checkpoint_callback
        if self.checkpoint_callback is None:
            if isinstance(logger, TestTubeLogger):
                ckpt_path = '{}/{}/{}'.format(self.default_save_path, self.logger.name,
                                              self.logger.version)
            else:
                ckpt_path = self.default_save_path

            self.checkpoint_callback = ModelCheckpoint(
                filepath=ckpt_path
            )
```

**Comment by williamFalcon** [comment]
good point. i guess we should modify how to manipulate those parameters?

Maybe we should do:
True (use the default)
False (don’t use)
Or the object for custom behavior?

This should apply to logger, checkpoint and early stop?

Default for all should be True

**Comment by neggert** [comment]
Sounds good to me
