### ISSUE TITLE
Progress bar no longer shows total iterations

### ISSUE THREAD

**Issue by neggert** [williamFalcon/pytorch-lightning#354]
This seems to have been introduced in master sometime recently. tqdm doesn't seem be be getting `total` set, so there's no progress bar or time to completion estimate. All we get is this:

```
374it [00:07, 50.48it/s, batch_nb=372, epoch=0, loss=0.801, some_val=1.25, v_nb=0]
```

**Comment by neggert** [comment]
This seems to be the culprit: https://github.com/williamFalcon/pytorch-lightning/pull/345/files#diff-0cd7170e96efa4a55577086f5db2fe4cR1058

@williamFalcon Was that line needed for some reason, or did some debug code just slip in?

**Comment by neggert** [comment]
Bah, link didn't point to where I wanted it to. The relevant code line in trainer.py is

```python
            # limit the number of batches to 1 in fast_dev_run
            self.total_batches = 1
```

**Comment by williamFalcon** [comment]
oh yeah... that's a bug

**Comment by williamFalcon** [comment]
but on fast_dev_run that should be 1
