### ISSUE TITLE
Support for retain_graph=True

### ISSUE THREAD

**Issue by momeara** [williamFalcon/pytorch-lightning#356]
**Is your feature request related to a problem? Please describe.**
Some models require retain_graph=True, but it's not possible to set it in the .backward() call inside of Trainer.__run_training_batch(...)

**Describe the solution you'd like**
Add train_graph member function the LightningModule have the trainer read this option and then pass it into the .backward() call.

**Describe alternatives you've considered**
Driving a version of Trainer to support retain_graph=True is tough because __run_training_batch and other functions are name-mangled.

**Comment by williamFalcon** [comment]
why don’t we put a hook for the backward pass and you can override if you need retain_graph?  that keeps it flexible for anything else someone wants to do later

**Comment by momeara** [comment]
perfect! that keeps with the overall philosophy, which has been very useful btw

**Comment by williamFalcon** [comment]
@yl1991 @momeara did you guys want to submit a PR for this?
