### ISSUE TITLE
Question regarding getting a version

### ISSUE THREAD

**Issue by seungwooYoo** [williamFalcon/pytorch-lightning#358]
Hi 

To my understanding, currently we could not getting a version of library such as pl.__version__.

If it is correct, then can you consider include a version number, which might help to handle significant version change like 0.4.x to 0.5.x. 

Thanks, :)

**Comment by williamFalcon** [comment]
good point @Borda any thoughts?

**Comment by Borda** [comment]
@seungwooYoo could you please be mo specific what you mean by getting version?
are you talking about instaling `pytorch-lightning` in a particular version?
then you can just install from pip 
```
pip instal pytorch-lightning==0.5.2
```
 any version available here: https://pypi.org/project/pytorch-lightning/#history
ar you can install it from GitHub directly 
```
pip install https://github.com/williamFalcon/pytorch-lightning/archive/0.4.9.zip
```
as you can see the releases here: https://github.com/williamFalcon/pytorch-lightning/releases

OR are you talking about PyTorch versions?

**Comment by neggert** [comment]
I think the OP is looking for something similar to `numpy.__version__`

**Comment by williamFalcon** [comment]
@Borda want to finish this PR? :) 
Almost there, but need to make sure that:
1. pip install -e . works

normal pip install works

**Comment by Borda** [comment]
sure, so you propose to replace `python setup.py install --dry-run` by `pip install -e .`

**Comment by williamFalcon** [comment]
no. 

pip install -e . is for local development

**Comment by Borda** [comment]
@williamFalcon I believe that it is ready - https://github.com/williamFalcon/pytorch-lightning/pull/395
