### ISSUE TITLE
moving examples out of the package

### ISSUE THREAD

**Issue by Borda** [williamFalcon/pytorch-lightning#36]
Hello, nice peace of work. I was wondering if it would be easier to have examples out of the package (more intuitive to finds and keep the package simple) as well as all tests?
(e.g. `pytorch-lightning/pytorch_lightning/testing_models/lm_test_module.py`)

**Comment by williamFalcon** [comment]
yeah, the problem was that there were issues with the test models being outside of the package. 

But if you want to make the change, feel free to submit a PR. 

Tests will also need to be update

**Comment by williamFalcon** [comment]
Awesome PR, thanks for submitting! Interested in looking at any of the other issues we need help with?

**Comment by Borda** [comment]
I was thinking about some workaround automatic testing, formation and coverage...
I will prepare another PR :)

**Comment by williamFalcon** [comment]
amazing! That would be great. Right now a big issue is having to manually run the GPU tests for free.

I'll create an issue to track these changes there

**Comment by gregunz** [comment]
I am new to python packages, modules and stuff but I think that now that the directory `examples` is in the root, the `setup.py` detects it as a package with `find_packages()`.

This results in anyone installing your `pytorch-lightning` package to also have a `examples` package installed into their environment.

As a matter of fact, it is preventing me from loading one of my local module named `examples`.

**Comment by gregunz** [comment]
The above commit could solve this.
It simply excludes the directory from the package.

Note that it also excludes the `tests` which should be causing the same type of problems.
I will proceed with a pull request if it makes sense to you @williamFalcon  @Borda.

**Comment by Borda** [comment]
I do agree with the change, or even explicitly name the 'pytorch-lightning'
Btw, why the package is imported `pytorch...` not just `torch...` such as PyTorch

**Comment by gregunz** [comment]
(I am not of my authority in this answer but: )

I also think `torch-lightning` makes a lot of sense.

**Comment by williamFalcon** [comment]
let’s keep it as is for now. i don’t want to introduce breaking changes often (pytorch-lightning)
