### ISSUE TITLE
setting gpus=-1 and gpus='-1' in Trainer give different behaviours

### ISSUE THREAD

**Issue by VismantasD** [williamFalcon/pytorch-lightning#367]
I discovered this while looking through the code. Trainer constructor does not mention that 
gpus can be -1 or '-1'. However if such values are passed they are accepted and result in
different behaviour: -1 will result in no gpus used, '-1' will use all available gpus.

**To Reproduce**
1. Run any model first setting trainer gpus parameter to -1. No gpus will be used.
2. Run same model setting gpus to '-1'. All available gpus will be used.

Being able to set -1 to indicate that all gpus should be used is and I believe useful behaviour.
The issue is in function [self.__parse_gpu_ids(gpus)](https://github.com/williamFalcon/pytorch-lightning/blob/19c2b8fc9e73326c3e320c29e8f932893bd49460/pytorch_lightning/trainer/trainer.py#L340) where the handling of -1 when passed as int is not implemented. 
Solution would be to implement equivalent logic for -1 as for '-1'.

Happy to submit a PR.

**Comment by williamFalcon** [comment]
yeah, fair. would love a PR! (also docs update)

**Comment by VismantasD** [comment]
Question. What is the intended behaviour when setting gpus in the Trainer to an int? (e2cabb03).
Is it specifying number of gpus to use? Or is it specifying a specific gpu? Depending on the choice one of __set_root_gpu() or num_gpus() needs fixing:
* If it is number of gpus, then __set_root_gpu  would be returning 0 but it should be returning None in this case.
* If it is specific gpu (e.g. gpus=3 means running on 3rd gpu) then num_gpus would be returning 3 instead of 1.

**Comment by williamFalcon** [comment]
number is for how many gpus to use. i guess the docs need to be updated to make that clear?

**Comment by VismantasD** [comment]
Thanks, Yeah, I think they could be more specific and it is hard to read it from code. I'll update the documentation in the PR.

**Comment by williamFalcon** [comment]
awesome!

**Comment by williamFalcon** [comment]
On master
