### ISSUE TITLE
Consider: ability to set seed

### ISSUE THREAD

**Issue by alok** [williamFalcon/pytorch-lightning#37]
I dunno if this is in scope (feel free to close if not), but when experimenting, setting a fixed seed is handy since you can remove one source of randomness (Karpathy's [recipe](https://karpathy.github.io/2019/04/25/recipe/) even includes it as an important beginning step).

Basically, being able to set the seeds for the `random`, `numpy`, `torch`, and other common modules in the config would be handy.

**Comment by williamFalcon** [comment]
setting the seed inside lightning seems like it hides too much according to ppl I’ve discussed with. i don’t want to have people wondering if lightning is doing anything with seeds

**Comment by sh0416** [comment]
How to set seed when I use 'ddp' for backend?
