### ISSUE TITLE
ModelCheckpoint does not save checkpoints

### ISSUE THREAD

**Issue by Menion93** [williamFalcon/pytorch-lightning#381]
This same code worked in the past version, but now it doesn't save the checkpoints anymore.

I tried with 
MODEL_OUTPUT = 'example/hello'
MODEL_OUTPUT = 'example/hello/'
MODEL_OUTPUT = 'example/hello/weights'

with 'example/hello/' as an existing folder 

```python
checkpoint_callback = ModelCheckpoint(
        filepath='%s/' % MODEL_OUTPUT,
        save_best_only=True,
        verbose=True,
        monitor='val_loss',
        mode='min'
    )

    early_stop_callback = EarlyStopping(monitor='val_loss', patience=5)

    tt_logger = CMLLogger(LOG_DIR)

    trainer = Trainer(logger=tt_logger,
                      row_log_interval=2,
                      checkpoint_callback=checkpoint_callback,
                      early_stop_callback=early_stop_callback,
                      gradient_clip_val=0.5,
                      gpus=gpus,
                      check_val_every_n_epoch=1,
                      max_nb_epochs=99999,
                      train_percent_check=train_frac,
                      log_save_interval=5,
                     )
```

**Desktop (please complete the following information):**
 - OS:linux/mac

**Comment by stas6626** [comment]
met this problem:) fixed by set train_percent_check=1

**Comment by Menion93** [comment]
Unfortunately I cannot set train_percent_check to 1 :(

**Comment by williamFalcon** [comment]
what train_frac are you using? are you using the latest version on master?

**Comment by Menion93** [comment]
The latest published release. I noticed now that train_frac is set to 1 in all of the examples above.

I forgot the mention that I'm subclassing a class that extends LightningModule as my model, in previous version this works fine.

**Comment by williamFalcon** [comment]
could you post full code or something? or code to reproduce?

**Comment by festeh** [comment]
Well, you seem to monitor `val_loss` in your callback, but you do not return it in the **separate** key in `validation_end`, if you're using latest version, this may be a problem, check sources https://github.com/williamFalcon/pytorch-lightning/blob/0fac2d64cf4c6c31d3b21605a272ace01d0c51a2/pytorch_lightning/trainer/trainer.py#L1304

**Comment by Menion93** [comment]
I see, I need to include the metrics in the parent node of the object, thank you

like this:

```python
{
    'log': {
        'val_loss': avg_loss,
        'val_acc': avg_acc,
    },
   'progress_bar': {
        'val_loss': avg_loss,
        'val_acc': avg_acc
    },
    'val_loss': avg_loss,
    'val_acc': avg_acc
}
```

**Comment by williamFalcon** [comment]
hadn't realized that wasn't the default. i agree that makes more intuitive sense. fixed on master
