### ISSUE TITLE
Typo in module's overview

### ISSUE THREAD

**Issue by heytitle** [williamFalcon/pytorch-lightning#40]
Hi,

Thanks for developing this module.
There is a small typo in the Lighting module's overview.

![overview_flat](https://user-images.githubusercontent.com/1214890/62454091-dc94d280-b79d-11e9-95ce-e9a6d2c0ba48.jpg)

**Comment by williamFalcon** [comment]
good catch. will update today!

thanks!

**Comment by williamFalcon** [comment]
actually, i think I can live with the typo haha. 
#pickYourBattles

But nevertheless, thanks for the catch!

If you want to look through docs or README for typos that would be super helpful! Then submit a PR with the fixes
:)

**Comment by williamFalcon** [comment]
If you are interested @heytitle, feel free to open up another issue and submit a PR!

**Comment by heytitle** [comment]
haha, 

You're welcome. Due to the fact that Hacktoberfest is coming, maybe you could label this issue with `hacktoberfest` or some something relevant.
