### ISSUE TITLE
Save/load hyperparameters with checkpoint

### ISSUE THREAD

**Issue by neggert** [williamFalcon/pytorch-lightning#406]
Right now, test tube users can have `model.load_from_metrics`, but there's no equivalent functionality for users of other logging frameworks. I believe we discussed a while ago that this functionality should be decoupled from logggers.

Proposal:
* When hyperparameters are stored as an `argparse.Namespace` in the `hparams` property of the model (as already required to get automatic hyperparam logging), save these parameters as part of checkpoints.
* Add a `load_from_checkpoint` classmethod to LightningModule that basically duplicates the functionality of `load_from_metrics`, but gets the hyperparameters from the checkpoint directly.

I'm happy to send a PR if this proposal looks okay.

**Comment by williamFalcon** [comment]
yeah that makes sense.

So in the checkpoint do:

```python
checkpoint['hparams'] = ...
```
?

That should be the standard going forward. Logging is nice for Testtube UI purposes to see what went into an experiment. But that's separate from loading weights imho.
