### ISSUE TITLE
Increment `global_step` at end of iter?

### ISSUE THREAD

**Issue by kossnick** [williamFalcon/pytorch-lightning#411]
`global_step` currently increments at the start of a batch: https://github.com/williamFalcon/pytorch-lightning/blob/f18aee30a530149524b7004b6215a08110dca653/pytorch_lightning/trainer/train_loop_mixin.py#L77

That means at `batch_nb` = 0, `global_step` = 1. Shouldn't `global_step` update at the end of the iter, so `batch_nb` = 0 when `global_step` = 0?

**Comment by williamFalcon** [comment]
fair point. feel free to make a PR!

**Comment by kossnick** [comment]
Here you go: https://github.com/williamFalcon/pytorch-lightning/pull/412
