### ISSUE TITLE
`validation_step` progress bar output should be used

### ISSUE THREAD

**Issue by kossnick** [williamFalcon/pytorch-lightning#420]
When you're running validation steps your progress bar iter counter will increment once per `validation_step`. However, AFAICT there's no way to actually customize the progress_bar text during these validation_steps. For large validation sets, this makes it hard to know how far into validation you are, since the iter counter is the total steps.

I am returning a dict from `validation_step` like:
```
def validation_step(self, batch, batch_nb):
	output = {'progress_bar': {'batch_nb': batch_nb}}
	return output
```

**Comment by williamFalcon** [comment]
@kossnick looks like this is possible. Want to submit a PR?
https://www.youtube.com/watch?v=8CE8SVNsUdg

I guess we could show the second validation bar underneath while the training loop bar is still on top.

This still doesn't solve the estimated loop completion though. For instance, an imagenet epoch might take a few hours and without accounting for the validation loop your time estimate would be very off. Not to mention people can request that only a portion of train/test/val are actually used...

So, maybe the way to do it is:
1. show bar 1 which has train+val length.
2. show bar 2 when val begins which shows only val_length.
  - update bar 1, 2 at the same time to make progress happen in both.
