### ISSUE TITLE
Automatic testing, formation and coverage refactoring

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#43]
Discussion on suggested changes to testing/formation/coverage by @Borda

**Comment by Borda** [comment]
@williamFalcon I have extended the CI so it runs overall package with `py.test` and checks basic PEP8 with `flake8`. Moreover, there are real badges, not fake ones like codecov and I have added CodeFactor.io which may help improve the code quality by suggestions in general and also in the time of PR... You may have look at updated sample project - https://github.com/Borda/py_sample-project

**Comment by williamFalcon** [comment]
Adding here again for clarity:

The code coverage badge was generated by doing this:
https://github.com/williamFalcon/pytorch-lightning/tree/master/tests#running-coverage

**Comment by Borda** [comment]
CircleCI does not offer any GPU plans for free. If you're interested in upgrading to a paid performance plan you can review the attached document... [Performance Plan - Pricing Infosheet Q1_19.pdf](https://github.com/williamFalcon/pytorch-lightning/files/3482293/Performance.Plan.-.Pricing.Infosheet.Q1_19.pdf)

This is the official reply from CircleCI, @williamFalcon have a look

**Comment by williamFalcon** [comment]
thanks for doing research on this. will stick to free for now ;)
