### ISSUE TITLE
Issue with multi gpu dp backend

### ISSUE THREAD

**Issue by srikarym** [williamFalcon/pytorch-lightning#436]
**Describe the bug**
I tried to run gpu_template.py from basic_examples but I get an error that says Fatal Python error:Aborted (screenshot below). I am able to use ddp but not dp. Did anyone else face this issue?

**Screenshots**
![image](https://user-images.githubusercontent.com/19867128/67629128-327e9100-f848-11e9-8b77-a474ee53fc0b.png)

**Comment by williamFalcon** [comment]
what versions are you running?
how are you running it? (cluster?, interactive mode?)
Do you have 2 gpus.

**Comment by srikarym** [comment]
Update - The same code worked when I ran it today. Don't know what the issue might have been.  
Versions - 
pytorch-lightning: 0.5.2.1
test-tube: 0.7.1          
torch: 1.3.0
I'm running it on a cluster in interactive mode. It has 2 gpus.
