### ISSUE TITLE
PackedSequence inputs gets converted to tuples of tensors

### ISSUE THREAD

**Issue by s-rog** [williamFalcon/pytorch-lightning#437]
**Describe the bug**
dataloaders returning 4 tensors (attributes of packed sequence) when collate_fn returns packed sequences

**To Reproduce**
```python
def collate_seq(batch):
    x = rnn.pack_sequence([item[0] for item in batch], enforce_sorted=False)
    y = rnn.pack_sequence([item[1] for item in batch], enforce_sorted=False)
    return x, y
```

**Expected behavior**
the x packed sequence gets passed to forward()

**Comment by williamFalcon** [comment]
when are you calling this function?
1. we can look into this. 
2. in the meantime you can collate in the beginning of training_step

**Comment by s-rog** [comment]
I implemented the latter solution as a workaround in both train and validation step and can confirm it works.

I used that collate_seq function as my collate_fn in train and val dataloaders. both x and y packed sequences are being passed into the model's functions as a tuple of (4) tensors. I've looked into the lightning source code but I haven't been able to find the source of the forced tensor conversion.

**Comment by williamFalcon** [comment]
Yeah, i think the assumption in lightning is that you pack the sentence in the beginning of training_step.

I usually pack and unpack right before going into the RNN.

```python
def forward(self, x):
  x = pack(x)
  out = rnn(x) 
  x = unpack(x)
```

**Comment by williamFalcon** [comment]
@s-rog that would be very helpful. Mind adding to docs and submitting a PR?
A better alternative would be a simple RNN example in the /examples folder documenting this.

**Comment by s-rog** [comment]
I looked into it again and it seems like this might be the source of the issue? @williamFalcon do you think this needs to be fixed? should be trivial to add another elif for packed sequences

https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/trainer/dp_mixin.py#L34

**Comment by williamFalcon** [comment]
ummm. yeah, submit the PR!
