### ISSUE TITLE
torch.cuda.empty_cache() adds memory allocation to gpu:0

### ISSUE THREAD

**Issue by fellnerse** [williamFalcon/pytorch-lightning#458]
**Describe the bug**
When running the gpu example with `--gpus=[1]` (this does not work, but setting the default to one gpu different then gpu 0 [here](https://github.com/williamFalcon/pytorch-lightning/blob/master/pl_examples/basic_examples/gpu_template.py#L56)) and `--distributed_backend=None` the system crashes while trying to forward `self.example_input_array`([here](https://github.com/williamFalcon/pytorch-lightning/blob/master/pl_examples/basic_examples/lightning_module_template.py#L38)):

```
Traceback (most recent call last):
  File "/home/sebastian/.cache/pypoetry/virtualenvs/pl-iterator-_1H-4oww-py3.7/src/pytorch-lightning/pytorch_lightning/root_module/memory.py", line 62, in get_variable_sizes
    out = m(input_)
  File "/home/sebastian/.cache/pypoetry/virtualenvs/pl-iterator-_1H-4oww-py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sebastian/.cache/pypoetry/virtualenvs/pl-iterator-_1H-4oww-py3.7/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/sebastian/.cache/pypoetry/virtualenvs/pl-iterator-_1H-4oww-py3.7/lib/python3.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:277
```

When I copy the whole thing and just comment this line it works again. But during `run_pretrain_routine` [emptying the cuda cache](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L464) somehow allocates 595mb on `gpu:0`.

**Expected behavior**
Only gpus specified for the trainer should be used all the time.

**Desktop (please complete the following information):**
Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
I cloned this commit version: https://github.com/williamFalcon/pytorch-lightning/commit/37729f0a17995e847fa8693f0fe694f8dd0b259b

Can someone verify that? Am I doing something wrong?

**Comment by Ir1d** [comment]
Did you run with `--gpus=2` or `CUDA_VISIBLE_DEVICES=2`

**Comment by fellnerse** [comment]
I replaces this [line](https://github.com/williamFalcon/pytorch-lightning/blob/master/pl_examples/basic_examples/gpu_template.py#L56) with `default=[1]`, and [this](https://github.com/williamFalcon/pytorch-lightning/blob/master/pl_examples/basic_examples/gpu_template.py#L62) with `default=None`:
```
    parent_parser.add_argument(
        '--gpus',
        type=int,
        default=[1],
        help='how many gpus'
    )
    parent_parser.add_argument(
        '--distributed_backend',
        type=str,
        default=None,
        help='supports three options dp, ddp, ddp2'
    )
```

I did not use any `CUDA_VISIBLE_DEVICES` stuff.

**Comment by williamFalcon** [comment]
@fellnerse you don't need to modify cuda flags (it's specifically mentioned in the docs).

Could you post the exact code you're using?

**Comment by fellnerse** [comment]
@williamFalcon Yes I know, that's what I was trying to say.

Here the complete code snipped:

```
"""
Runs a model on a single node across N-gpus.
"""
import os
from argparse import ArgumentParser

import numpy as np
import torch

from pytorch_lightning import Trainer

# from lightning_module_template import LightningTemplateModel
from pl_examples.basic_examples.lightning_module_template import LightningTemplateModel

SEED = 2334
torch.manual_seed(SEED)
np.random.seed(SEED)


def main(hparams):
    """
    Main training routine specific for this project
    :param hparams:
    """
    # ------------------------
    # 1 INIT LIGHTNING MODEL
    # ------------------------
    model = LightningTemplateModel(hparams)

    # ------------------------
    # 2 INIT TRAINER
    # ------------------------
    trainer = Trainer(
        gpus=hparams.gpus,
        distributed_backend=hparams.distributed_backend,
        use_amp=hparams.use_16bit
    )

    # ------------------------
    # 3 START TRAINING
    # ------------------------
    trainer.fit(model)


if __name__ == '__main__':
    # ------------------------
    # TRAINING ARGUMENTS
    # ------------------------
    # these are project-wide arguments

    root_dir = os.path.dirname(os.path.realpath(__file__))
    parent_parser = ArgumentParser(add_help=False)

    # gpu args
    parent_parser.add_argument(
        '--gpus',
        type=int,
        default=[1],
        help='how many gpus'
    )
    parent_parser.add_argument(
        '--distributed_backend',
        type=str,
        default=None,
        help='supports three options dp, ddp, ddp2'
    )
    parent_parser.add_argument(
        '--use_16bit',
        dest='use_16bit',
        action='store_true',
        help='if true uses 16 bit precision'
    )

    # each LightningModule defines arguments relevant to it
    parser = LightningTemplateModel.add_model_specific_args(parent_parser, root_dir)
    hyperparams = parser.parse_args()

    # ---------------------
    # RUN TRAINING
    # ---------------------
    main(hyperparams)
```
I run it without flags or command line arguments.
The only difference to the original are the default values for `--gpus` and `--distributed_backend`.

**Comment by fellnerse** [comment]
This seems to be more related to pytorch then pytorch lightning...will close if nobody can replicate this.

**Comment by xinfangliu** [comment]
I have the same problem, when mem in gpu0 is not enough, Cuda out of memory error occurs
