### ISSUE TITLE
absolute/relative imports

### ISSUE THREAD

**Issue by Borda** [williamFalcon/pytorch-lightning#459]
@williamFalcon suggest using absolute import inside the package https://github.com/williamFalcon/pytorch-lightning/pull/402#issuecomment-544704568
I would like to discuss a bit on the advantages/drawback of both since I have seen more often relative imports then the absolute, for example, `scikit-learn`

See:
- https://realpython.com/absolute-vs-relative-python-imports/
- https://stackabuse.com/relative-vs-absolute-imports-in-python/
- https://stackoverflow.com/questions/4209641/absolute-vs-explicit-relative-import-of-python-module

**Comment by williamFalcon** [comment]
@Borda let's chat on the forum but i lean on keeping them absolute again, since it's clear where the import comes from.

**Comment by Borda** [comment]
ok, my thought was that with relative imports it does not interfere with already (locally) installed version while you are running tests and some function/module/package changed in developed version...
