### ISSUE TITLE
Nitpick: `ptl` may be better as `pl`

### ISSUE THREAD

**Issue by alok** [williamFalcon/pytorch-lightning#46]
(Feel free to ignore.)

All the usage examples do `import pytorch_lighting as ptl`. Instead of `ptl`, `pl` may  be better as it doesn't clash with any library I know of, is 2 characters like NumPy's `np`, and is harder to mistype as `plt`, which many researchers probably also have imported. Since the library is in its early days, I don't think it would be that dramatic a change and is a little easier to read for people like me who often mix up letters like that.

On the other hand, it's pretty clear that it's not matplotlib from context, is yet another change, and is an aesthetic choice at its root, so it may not be worth it.

**Comment by williamFalcon** [comment]
Good point. I forgot about matplotlib (plt) lol. I would for sure mess that up.   

Do you want to submit a PR changing docs and examples from ptl to pl?
