### ISSUE TITLE
Full ImageNet training example

### ISSUE THREAD

**Issue by zphang** [williamFalcon/pytorch-lightning#475]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be good to have a full ImageNet training example in the vein of https://github.com/pytorch/examples/tree/master/imagenet to showcase a complete Lightning project.

**Describe alternatives you've considered**
N/A

**Additional context**
I'm happy to prototype a version!

**Comment by williamFalcon** [comment]
sweet. good addition
