### ISSUE TITLE
About the Weight Initialization in PL

### ISSUE THREAD

**Issue by magic282** [williamFalcon/pytorch-lightning#477]
Hi,

I am tring to use BERT for a project. The pretrained BERT model is part of my model. I am wondering how will PL initialize the model weights. Will it overwrite the pretrained BERT weights?

Thanks.

**Comment by williamFalcon** [comment]
lightning doesn’t do any magic like this under the hood. you control all the weights and what gets initiated

**Comment by magic282** [comment]
I see. So where should I do the weight initialization step? In the `__init__` of `pl.LightningModule`

**Comment by williamFalcon** [comment]
This is up to you and you should follow standard PyTorch guidelines.
Normally it's done in __init__
