### ISSUE TITLE
How set number of epochs

### ISSUE THREAD

**Issue by Vichoko** [williamFalcon/pytorch-lightning#483]
How do I set the number of epochs to train?

#### What have you tried?    
Looking for documentation. 
Looking for examples.

**Comment by williamFalcon** [comment]
https://pytorch-lightning.readthedocs.io/en/latest/Trainer/Training%20Loop/#force-training-for-min-or-max-epochs

**Comment by npit** [comment]
Up-to-date link: 
https://pytorch-lightning.readthedocs.io/en/latest/pytorch_lightning.trainer.training_loop.html#force-training-for-min-or-max-epochs

**Comment by ashutosh-dwivedi-e3502** [comment]
Up-to-date link : 
https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#max-epochs
