### ISSUE TITLE
IterableDataset breaks 1.1 compatibility

### ISSUE THREAD

**Issue by volcacius** [williamFalcon/pytorch-lightning#491]
A recently introduced feature unfortunately breaks compability with Pytorch 1.1.0. 

**Describe the bug**
IterableDataset support, introduced in [issue 323](https://github.com/williamFalcon/pytorch-lightning/issues/323), requires Pytorch 1.2.0+.    

**To Reproduce**
In a python environment with Pytorch 1.1.0 do:
import pytorch_lightning

**Expected behavior**
Compatibility with Pytorch 1.1.0. I'm filing it as a bug report rather than a docs fix since the dependency on 1.2.0+ introduced by [issue 323](https://github.com/williamFalcon/pytorch-lightning/issues/323) doesn't seem to be intentional.

**Comment by williamFalcon** [comment]
good catch. mind submitting a PR? was not the intention of that fix :)

We want to support 1.1

**Comment by Borda** [comment]
I have played with versions and it seems to me that it does not run even with 1.2.0; see #462

**Comment by williamFalcon** [comment]
weird. let’s patch it and put a note on the readme to use 0.5.2.1 if you need pt 1.1 or 1.2 support?

**Comment by Borda** [comment]
you may rather change requirements.txt and after fix put it back...
I see that >=1.2.0 is there already for some time... 8-)

**Comment by shreyasbapat** [comment]
Is this already fixed? I see that torch 1.2.0 is already in requirements.txt ?

**Comment by Borda** [comment]
I think not yet...8-)

**Comment by shreyasbapat** [comment]
Do you suggest torch 1.3.0 ?

**Comment by williamFalcon** [comment]
we need to support 1.2.0 :)

**Comment by williamFalcon** [comment]
@Borda did we get this fixed? is PT 1.2 supported now? If not, what do we need to do?

**Comment by Borda** [comment]
I have not worked on it yet (bit busy with docs), hopefully this week...
