### ISSUE TITLE
Is requirement numpy==1.16.4 really needed ?

### ISSUE THREAD

**Issue by cedias** [williamFalcon/pytorch-lightning#519]
Hi,

While installing ligthning via pip I saw that the numpy requirements was fixed to version 1.16.4:

> ERROR: pytorch-lightning 0.5.3.2 has requirement numpy==1.16.4, but you'll have numpy 1.17.4 which is incompatible.

After a quick scroll through the source code i'm wondering:  is there a reason why this requirement is so specific ?

Also, wouldn't it make more sense to use pytorch tensors to try and drop the numpy requirements ?  Or at least, drop the == 1.16.4

**Comment by williamFalcon** [comment]
nah. it’s a typo. Mind submitting a PR?

great catch!

**Comment by cedias** [comment]
Here you go : #520

**Comment by Borda** [comment]
@williamFalcon we already have it here #500 waiting for you...

**Comment by cedias** [comment]
>  wouldn't it make more sense to use pytorch tensors to try and drop the numpy requirements ? 

It's probably worth noting that searching "numpy" within lightning codebase yields only 13 results...

**Comment by Borda** [comment]
Do you know a person using Python who doesn't have installed `numpy` directly or as dependence? =)

**Comment by williamFalcon** [comment]
Fixed in #500
