### ISSUE TITLE
Checkpoint saving period=10 off by one error

### ISSUE THREAD

**Issue by nspotrepka** [williamFalcon/pytorch-lightning#527]
**Describe the bug**
Checkpoint saving period=10 sometimes is off by one:
./checkpoints/_ckpt_epoch_10.ckpt
./checkpoints/_ckpt_epoch_20.ckpt
./checkpoints/_ckpt_epoch_30.ckpt
./checkpoints/_ckpt_epoch_40.ckpt
./checkpoints/_ckpt_epoch_50.ckpt
./checkpoints/_ckpt_epoch_60.ckpt
./checkpoints/_ckpt_epoch_70.ckpt
./checkpoints/_ckpt_epoch_80.ckpt
./checkpoints/_ckpt_epoch_90.ckpt
./checkpoints/_ckpt_epoch_100.ckpt
./checkpoints/_ckpt_epoch_110.ckpt
./checkpoints/_ckpt_epoch_120.ckpt
./checkpoints/_ckpt_epoch_130.ckpt
./checkpoints/_ckpt_epoch_140.ckpt
./checkpoints/_ckpt_epoch_150.ckpt
./checkpoints/_ckpt_epoch_160.ckpt
./checkpoints/_ckpt_epoch_170.ckpt
./checkpoints/_ckpt_epoch_180.ckpt
./checkpoints/_ckpt_epoch_191.ckpt

Another time, it incremented at 61 and then again at 192.

**To Reproduce**
No idea why this is happening. It's very random!

**Expected behavior**
The expected behavior is that it saves every 10 epochs exactly.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS

**Additional context**
Saving a checkpoint every 10 epochs.
```
    checkpoint = ModelCheckpoint(
        filepath=os.path.join(os.getcwd(), 'checkpoints'),
        verbose=True,
        save_best_only=False,
        save_weights_only=False,
        period=10
    )
    if setup.cuda_is_available():
        trainer = Trainer(
            distributed_backend='dp',
            gpus=setup.cuda_device_count(),
            checkpoint_callback=checkpoint,
            early_stop_callback=None,
            max_nb_epochs=params.epochs
        )
    else:
        trainer = Trainer(
            checkpoint_callback=checkpoint,
            early_stop_callback=None,
            max_nb_epochs=params.epochs
        )
```

**Comment by williamFalcon** [comment]
@Ir1d

**Comment by Borda** [comment]
is the `./checkpoints/_ckpt_epoch_191.ckpt` the last one... and if it off does it hold the offset?
@nspotrepka do you have another example from your output? :)

**Comment by Ir1d** [comment]
Did you use the latest master or the previous release?

**Comment by Ir1d** [comment]
Did you use the latest master or the previous release?

**Comment by nspotrepka** [comment]
@Borda yes it holds the offset

Another example from my own memory, since I deleted the files:
./checkpoints/_ckpt_epoch_10.ckpt
./checkpoints/_ckpt_epoch_20.ckpt
./checkpoints/_ckpt_epoch_30.ckpt
./checkpoints/_ckpt_epoch_40.ckpt
./checkpoints/_ckpt_epoch_50.ckpt
./checkpoints/_ckpt_epoch_61.ckpt
./checkpoints/_ckpt_epoch_71.ckpt
./checkpoints/_ckpt_epoch_81.ckpt
./checkpoints/_ckpt_epoch_91.ckpt
./checkpoints/_ckpt_epoch_101.ckpt
./checkpoints/_ckpt_epoch_111.ckpt
./checkpoints/_ckpt_epoch_121.ckpt
./checkpoints/_ckpt_epoch_131.ckpt
./checkpoints/_ckpt_epoch_141.ckpt
./checkpoints/_ckpt_epoch_151.ckpt
./checkpoints/_ckpt_epoch_161.ckpt
./checkpoints/_ckpt_epoch_171.ckpt
./checkpoints/_ckpt_epoch_181.ckpt
./checkpoints/_ckpt_epoch_192.ckpt

**Comment by nspotrepka** [comment]
@Ir1d pytorch-lightning 0.5.3.2

**Comment by Borda** [comment]
@nspotrepka to reaction on @Ir1d pls install from lat master
btw, do you have a sample code we can run to replicate your issue?

**Comment by Ir1d** [comment]
the modelchecking strategy changed a bit in latest master, you might want to try it out.
Please note that epoch number starts from 0 now.

**Comment by jeffling** [comment]
Do you have any overrides related to checkpoints, like state_dict? or anything setting should_checkpoint?

Noticed you have DP settings as well, does the error happen without DP?

**Comment by williamFalcon** [comment]
@nspotrepka how did it go with the suggested fixes?

**Comment by nspotrepka** [comment]
I'm now saving the best model only, so I'm no longer looking at this issue.
