### ISSUE TITLE
Summary not working for model on GPU with multiple inputs

### ISSUE THREAD

**Issue by VSJMilewski** [williamFalcon/pytorch-lightning#537]
**Describe the bug**
When you want a summary for a model that requires multiple input parameters for forward, then this doesn't work. You can set self.example_input_array to be a tuple and there is some code for passing this to the forward method. However, if the model is on cuda, it tries to pass to move this input directly to cuda without a check whether it is a tuple or list.

the line with the error is here: 
[pytorch-lightning/blob/master/pytorch_lightning/root_module/memory.py#L53](https://github.com/williamFalcon/pytorch-lightning/blob/7324dd902b8d071f4889ab1274a4d4dc09de9a78/pytorch_lightning/root_module/memory.py#L53)

example of how it should be checked: 
[pytorch-lightning/blob/master/pytorch_lightning/root_module/memory.py#L61](https://github.com/williamFalcon/pytorch-lightning/blob/7324dd902b8d071f4889ab1274a4d4dc09de9a78/pytorch_lightning/root_module/memory.py#L61)

**To Reproduce**
1. create a model that requires multiple inputs in the forward method. 
2. set self.example_input_array to be a tuple
3. run the model on GPU

**Expected behavior**
a list with all layers and the input and output shapes of these layers. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6348139/69352469-4bc70180-0c7d-11ea-88c6-8056ab531c80.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2
 - Browser chrome
 - Version 8.0.3904.97 (Official Build) (64-bit)

**Comment by williamFalcon** [comment]
@victormilewski1994 good point. I guess we didn't specifically design the summarizer to take in multiple inputs. Would you be interested in submitting a PR?
