### ISSUE TITLE
Image logging to tensorboard

### ISSUE THREAD

**Issue by tmquan** [williamFalcon/pytorch-lightning#54]
Hi @williamFalcon , 

Thanks for your nice work. 
I am just wondering is it possible to log the image tensor to tensorboard to train such a U-net?

Bests,

**Comment by williamFalcon** [comment]
yup! 

in the lightningModule you can call self.experiment. that’s a summarywriter for tensorboard. for the api of that refer to pytorch summarywriter.  

https://pytorch.org/docs/stable/tensorboard

it’s all explained here:  https://williamfalcon.github.io/pytorch-lightning/Trainer/Logging/#tensorboard-support


realized self.experiment from docs. adding now!

**Comment by williamFalcon** [comment]
@tmquan can you update to the latest test-tube version and try again?

**Comment by Ceceu** [comment]
Is there an approach to only log a subset of images instead of all over the `validation_step` or `test_step` call?

**Comment by epignatelli** [comment]
I don't think it's a feasible solution.

It means returning the outputs of the forward pass from `training_step`.

However, as soon as you override `training_epoch_end`, it will stack things up in the GPU, until it crashes.

**Comment by ananyahjha93** [comment]
@Ceceu have you tried
```
torchvision.utils.make_grid()
```
and then log images?

**Comment by ananyahjha93** [comment]
@epignatelli you can create a variable such as 

```
self.imgs = # something
```
and then plot these. This will work with DDP and the regular single GPU case but will not work with DP the default version does not support state maintenance.

**Comment by williamFalcon** [comment]
example:

https://pytorch-lightning-bolts.readthedocs.io/en/latest/vision_callbacks.html#confused-logit

**Comment by Ceceu** [comment]
Thanks @ananyahjha93 and @williamFalcon, I guess the callback approach is the best practice.

**Comment by qmpzzpmq** [comment]
Hi, right now is there any method to call tensorboard's `add_image` `add_audio`

**Comment by tmquan** [comment]
@qmpzzpmq 
There should be 
``` python
tensorboard = self.logger.experiment
grid = torchvision.utils.make_grid(...)
tensorboard.add_image(f'{stage}_samples', grid.clamp(0., 1.), self.current_epoch*self.batch_size + batch_idx)    
```
