### ISSUE TITLE
object has no attribute 'add_scalar'

### ISSUE THREAD

**Issue by brucemuller** [williamFalcon/pytorch-lightning#544]
I'm trying to use the default logger to record scalars for tensorboard using add_scalar but I get:
   
 self.logger.add_scalar('loss/train_loss', 42, 42)
AttributeError: 'TestTubeLogger' object has no attribute 'add_scalar'

The docs say TestTubeLogger inherits from SummaryWriter so add_scalar should be ok.
Can anyone help?

#### What's your environment?   
- conda version (no venv) : 4.7.12  
- PyTorch version: 1.3.1
- Lightning version: 0.5.3.2
- Test-tube version: 0.7.3

**Comment by williamFalcon** [comment]
self.logger.experiment

**Comment by SylarZiling** [comment]
> self.logger.experiment.add_scalar

sorry I have similar problem, I used the experiment still tells me no attribute 'add_scalar" 

    self.logger.experiment.add_scalar(f'metrics_{valset_idx}/{k}', v, global_step=cur_epoch)
AttributeError: 'list' object has no attribute 'add_scalar'

and this is experiment  [<torch.utils.tensorboard.writer.SummaryWriter object at 0x7f3af4baf990>]
