### ISSUE TITLE
`trainer.on_gpu == True` for `gpus = 0` or `gpus=[]`

### ISSUE THREAD

**Issue by mpariente** [williamFalcon/pytorch-lightning#558]
**Describe the bug**
`trainer.on_gpu == True` for `gpus = 0` or `gpus=[]` because of [this line](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L135).
When resuming from a checkpoint, the model is transfered to gpu at [this line](https://github.com/williamFalcon/pytorch-lightning/blob/9785a3e78e6c5b5ff2bde45d36f5e1165dbe16ab/pytorch_lightning/trainer/trainer_io.py#L171), even if `gpus=0`

**Expected behavior**
`gpus=0` should make training happen on CPU.

I can make a PR for that, the fix is pretty simple, I think we can just replace
`self.on_gpu = gpus is not None and torch.cuda.is_available()`
by 
`self.on_gpu = True if (gpus and torch.cuda.is_available()) else False`

Am I missing something?

**Comment by williamFalcon** [comment]
to use no gpus just set 
```
gpu=None
```
If you think that gpus=0 or gpus=[] should also run on no GPUs feel free to submit a PR
