### ISSUE TITLE
logger: add TensorBoard without tensorFlow

### ISSUE THREAD

**Issue by Borda** [williamFalcon/pytorch-lightning#588]
**Is your feature request related to a problem.**
any way to get rid of the TensorFlow dependency?

**Describe alternatives you've considered**
See discussion in #265.

**Additional context**
- https://gist.github.com/wchargin/d3ab370042a3a2c66c495ef814c36354
- https://gist.github.com/gyglim/1f8dfb1b5c82627ae3efcfbbadb9f514#gistcomment-3010311

**Comment by awaelchli** [comment]
Found some additional info.
The FAQ in the tensorboard [readme](https://github.com/tensorflow/tensorboard#can-i-run-tensorboard-without-a-tensorflow-installation) states:

Can I run tensorboard without a TensorFlow installation?
TensorBoard 1.14+ can be run with a reduced feature set if you do not have TensorFlow installed. The primary limitation is that as of 1.14, only the following plugins are supported: scalars, custom scalars, image, audio, graph, projector (partial), distributions, histograms, text, PR curves, mesh. In addition, there is no support for log directories on Google Cloud Storage.

**Comment by awaelchli** [comment]
As far as I know, PyTorch provides the SummaryWriter but does not have TensorBoard/TensorFlow as a requirement.

**Comment by Borda** [comment]
@awaelchli nice, are you interested in submitting a PR? :]

**Comment by williamFalcon** [comment]
yes! this is a big addition. @awaelchli or @neggert would anyone be interested in adding this today so we can have it in the next release?

**Comment by awaelchli** [comment]
would be interested. However, I have unfortunately no time today. @neggert feel free to take it if you have the time.

**Comment by williamFalcon** [comment]
here are clear instructions on how to do this:

https://pytorch-lightning.readthedocs.io/en/latest/Trainer/Logging/#custom-logger

**Comment by neggert** [comment]
I think I have a little time today to take a crack at it.
