### ISSUE TITLE
codecov not updating

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#59]
Awesome improvements to coverage and tests! thanks @Borda 

Wondering what has to be done to update the badge now. I pushed a report from GPU coverage but no updates.

@Borda

**Comment by Borda** [comment]
Pls have look at the parameters `codecov --help` I guess that you need to specify the commit or something like this... unfortunately I was using automatic mode for most of my project so this is a bit new for me... Also, we can ask Codecov support for advice...

**Comment by williamFalcon** [comment]
ok. in the meantime let’s roll back to the original badge. this is critical during the early adoption period. 

once the auto thing is figured out we can roll back

**Comment by williamFalcon** [comment]
i’ll try one more time from master. maybe i have to run codecov on master and push directly. if that fails, we use the old static badge.

**Comment by williamFalcon** [comment]
rolled back the badge until the other one works.

I don't want to add unnecessary friction or mistrust at this stage in the project. If the other badge works, then great. Otherwise we'll keep doing it manually.

**Comment by Borda** [comment]
Then I would move the badge image to the docs folder...
