### ISSUE TITLE
map_location hasn't been implemented in load_from_checkpoint

### ISSUE THREAD

**Issue by haossr** [williamFalcon/pytorch-lightning#600]
**Describe the bug**
Current `load_from_checkpoint` function does not support to load a gpu checkpoint on cpu devices, i.e. map the location. 

**To Reproduce**
```
# on a cpu only device:
Model.load_from_checkpoint("GPU_CHECKPOINT_FILE")
```

**Expected behavior**
`AssertionError: Torch not compiled with CUDA enabled`

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.1
 - Browser: chrome
 - Version: 0.5.3.1

**Comment by williamFalcon** [comment]
weird, i thought we did. mind submitting a PR?

**Comment by haossr** [comment]
Sure will do.

**Comment by gaoalexander** [comment]
This appears to still be unresolved, currently using Lightning 2.3.0.
