### ISSUE TITLE
DDP support on Jupyter Notebook

### ISSUE THREAD

**Issue by egonuel** [williamFalcon/pytorch-lightning#61]
I'm trying to get ddp, fp16 etc running, however just setting the gpus and the `distributed_backend='ddp'` lets the CoolModel demo crash on my machine. I'm running it from a jupyter notebook with python 3.6 on a Ubuntu 18.04 machine with 2xV100.
The errors directly in the notebook are:

> Exception                                 Traceback (most recent call last)
<ipython-input-8-3a22b74b1d8d> in <module>
     69 
     70 # train (1 epoch only here for demo)
---> 71 trainer.fit(model)
     72 
     73 # view tensorflow logs

> /opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/pytorch_lightning/models/trainer.py in fit(self, model)
    425                 """
    426                 warnings.warn(msg)
--> 427                 mp.spawn(self.ddp_train, nprocs=len(self.data_parallel_device_ids), args=(model, ))
    428 
    429         # 1 gpu or dp option triggers training using DP module

> /opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py in spawn(fn, args, nprocs, join, daemon)
    165 
    166     # Loop on join until it returns True or raises an exception.
--> 167     while not spawn_context.join():
    168         pass

> /opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    106                 raise Exception(
    107                     "process %d terminated with exit code %d" %
--> 108                     (error_index, exitcode)
    109                 )
    110 

> Exception: process 0 terminated with exit code 1

and in the jupyter server output window:

> Traceback (most recent call last):                                                                                      
  File "<string>", line 1, in <module>                                                                                
  File "/opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main 
    exitcode = _main(fd)                                                                                              
  File "/opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/multiprocessing/spawn.py", line 115, in _main        
    self = reduction.pickle.load(from_parent)                                                                           
AttributeError: Can't get attribute 'CoolModel' on <module '__main__' (built-in)>  

I installed apex as it is written it the repository.

**Comment by williamFalcon** [comment]
sorry, i think this was caused by adding relative imports and i think u might run into issues for the next few hours. 

i’m going to change back all those imports to be absolute which will fix these issues.

**Comment by egonuel** [comment]
I forgot to mention that I'm trying this on the latest release installed using pip, not the one I github one I used in my other issue.

**Comment by williamFalcon** [comment]
can you post the code? seems strange

**Comment by egonuel** [comment]
okay it appears that this has to do with the fact that the CoolModel() is defined in the jupyter notebook. I now put it into a .py file (and added a distributed sampler) and the error is gone. This seems to have something to do with the spawning and pickle. This is a bit of limitation while working with notebooks...

However I now run into other issues:
I create the trainer like this `trainer = Trainer(experiment=exp, max_nb_epochs=1, distributed_backend='ddp', gpus=[0])`, when letting it run it creates a tensorboard log file, which is visible in tensorboard, but tensorboard does not show any data.

In addition the progress bar is not present in the notebook anymore, but in the log output in the terminal of jupyter.

**Comment by williamFalcon** [comment]
@egonuel can you post the full code? I definetely use this on notebooks with v100s without issues. need to see what you're doing.

**Comment by williamFalcon** [comment]
btw... lightning doesn't allow DDP for single GPUs. you have to use 2 because the connection is unstable otherwise. Just put 2 gpus on the notebook.

**Comment by egonuel** [comment]
@williamFalcon my model in coolmodel.py looks like this:
```

import os
import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
import torchvision.transforms as transforms

import pytorch_lightning as pl

class CoolModel(pl.LightningModule):

    def __init__(self, distributed=False):
        super(CoolModel, self).__init__()
        self.distributed = distributed

        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def my_loss(self, y_hat, y):
        return F.cross_entropy(y_hat, y)

    def training_step(self, batch, batch_nb):
        x, y = batch
        y_hat = self.forward(x)
        loss_val = self.my_loss(y_hat, y)
        if self.trainer.use_dp:
            loss_val = loss_val.unsqueeze(0)
        return {'loss': loss_val}

    def validation_step(self, batch, batch_nb):
        x, y = batch
        y_hat = self.forward(x)
        loss_val = self.my_loss(y_hat, y)
        if self.trainer.use_dp:
            loss_val = loss_val.unsqueeze(0)
        return {'val_loss': loss_val}

    def validation_end(self, outputs):
        avg_loss = torch.stack([x['val_loss'] for x in outputs]).mean()
        return {'avg_val_loss': avg_loss}

    def configure_optimizers(self):
        return [torch.optim.Adam(self.parameters(), lr=0.02)]

    @pl.data_loader
    def tng_dataloader(self):
        dataset = MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor())
        if self.distributed:
            dist_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
            return DataLoader(dataset, batch_size=32, sampler=dist_sampler)
        return DataLoader(dataset, batch_size=32)

    @pl.data_loader
    def val_dataloader(self):
        dataset = MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor())
        if self.distributed:
            dist_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
            return DataLoader(dataset, batch_size=32, sampler=dist_sampler)
        return DataLoader(dataset, batch_size=32)

    @pl.data_loader
    def test_dataloader(self):
        dataset = MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor())
        if self.distributed:
            dist_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
            return DataLoader(dataset, batch_size=32, sampler=dist_sampler)
        return DataLoader(dataset, batch_size=32)
```

and the code in my notebook like this:
```
import os
import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
import torchvision.transforms as transforms


from coolmodel import CoolModel
from pytorch_lightning import Trainer
from test_tube import Experiment

model = CoolModel(distributed=True)
exp = Experiment(save_dir=os.getcwd())

trainer = Trainer(experiment=exp, max_nb_epochs=1, train_percent_check=1.0,
                 distributed_backend='ddp',
                 gpus=[0],
#                  amp_level='O2', use_amp=True
                 )

trainer.fit(model)
```

I play with turning `distributed_backend` on and off, one or two gpus and fp16.

**Comment by williamFalcon** [comment]
ok, and it this doesn't work?
what doesn't work?
does it train?

is it only the logging that isn't showing up? (tensorboard has issues with jupyter notebook). 
Check #28

**Comment by williamFalcon** [comment]
what happens if you do exp.close()?

**Comment by egonuel** [comment]
it does not create meta_tags.csv and metrics.csv once I turn on ddp

**Comment by williamFalcon** [comment]
ummm.. yeah not sure, will have to look at it. I'll run an example in a bit.

what about no 16 bit and DP?

**Comment by egonuel** [comment]
this was with no 16 bit.
If I use DP it creates the files and tensorboard displays their data.

**Comment by williamFalcon** [comment]
ok, so it works fine in that case.

yeah, i'm not sure about DDP on notebooks. DDP does a lot of stuff behind the scenes that needs a closer look.

specifically it spawns multiple processes but I don't know what the issues are with the notebook which might be on a different process

i'm not convinced DDP is made to be run on notebooks. I would debug/etc using DP on a single GPU and run actual .py files using DDP in the meantime.

**Comment by williamFalcon** [comment]
@egonuel assuming this is a non-trivial thing to support, I've changed this issue to reflect a feature request which is DDP support on jupyter-notebook.

However, don't know the PyTorch limitations on this, but will look at it some time this week.
In the meantime, i'd suggest the flow I mentioned:
1. debug using DP
2. Use DDP on a .py file.

Although... you did mention it trained fine using ddp? is that correct? it's just the logging that isn't showing?

**Comment by egonuel** [comment]
well it trained and the progress bar showed a reducing loss. Right now I don't have any facilities ready to get more insights. As you say, the logging to the tensorboard files is not working and the progress bar is not in the notebook.
As a side note: I'm using fast.ai until now and it took me quite some time to customize it to let me do what I have to do. I like the idea of having a more flexible library like yours and I'm trying to get the nice things of fast.ai like progress plotting etc running with your library as well.

**Comment by egonuel** [comment]
there is a [fast.ai document](https://github.com/fastai/fastai/blob/master/docs/distributed.md), where they state that distributed training does not work in notebooks and it appears that they use DDP as well. 
What's nice about fast.ai is that their fp16 support works without DDP. For apex this probably related to the issue you mention in your code.

**Comment by williamFalcon** [comment]
yeah... i mean,  16 bit with a single GPU on lightning is easy to support. so, i'll make that change now, but DP + 16-bit is not up to us. Maybe fast.ai is using an older version of PyTorch where that makes sense.

**Comment by egonuel** [comment]
Okay, nice! I have just this one machine with the two V100 and hence many times it is useful for me to run different things on both of them, but still use fp16 to decrease the running time...

**Comment by williamFalcon** [comment]
@egonuel see #66 it's going through the test process now but it's supported there. give it an hour or so and it'll be on master

**Comment by williamFalcon** [comment]
@egonuel once you get it working would be great if you could tweet a screenshot! @me and PytrochLightnin...  :)

**Comment by williamFalcon** [comment]
@egonuel merged to master! let me know how it works.

**Comment by egonuel** [comment]
@williamFalcon it works now :) Did you mean I should put that screenshot on twitter?
Regarding putting the model into a py file: It's not neccessary if one does not use DDP. Only with DDP it has to be done as the multiprocessing uses pickle to distribute it. At least as far as I understand.
There is a module called dill which replaces pickle and is supposed to be able to work with notebooks etc, however this is more a pytorch thing I guess.

**Comment by s-rog** [comment]
@williamFalcon 
I know this might be beyond the scope of lightning, but do you have any more info regarding ddp support in notebooks?
