### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by lemairecarl** [williamFalcon/pytorch-lightning#623]
In the section https://github.com/williamFalcon/pytorch-lightning#what-does-lightning-control-for-me there is a large jpg. In the section "DATA SETUP" it says "Augmets" instead of "Augments".

If that image was generated from LaTeX, or if it was an svg, anybody in the community could edit it.

**Comment by Borda** [comment]
Thx for catching the typo, @williamFalcon how the image was created?

**Comment by williamFalcon** [comment]
new gif

**Comment by lemairecarl** [comment]
wowz!1
