### ISSUE TITLE
Call or Forward?

### ISSUE THREAD

**Issue by keunwoochoi** [williamFalcon/pytorch-lightning#632]
Hi, thanks for the nice library. In the `readme`, the example uses  `model.forward(x)` not `model(x)`. But wouldn't it usually recommended to use `model(x)` so that other things (hooks etc) can be, well, hooked as well? What's the best practice?

**Comment by williamFalcon** [comment]
forward should implement what you want to use when calling model(x). 

you may need to call that in training step (usually do), which means you have to do self.forward(...) because you are in the model when you make that call.
