### ISSUE TITLE
Turn off validation if val_percent_check=0

### ISSUE THREAD

**Issue by kuynzereb** [williamFalcon/pytorch-lightning#646]
As was suggested by @williamFalcon in https://github.com/williamFalcon/pytorch-lightning/issues/536#issuecomment-558115605 `val_percent_check=0` should turn off the validation loop. But now it will not work because of
```
 self.num_val_batches = max(1, self.num_val_batches)
```
So I suggest to fix it. Moreover I suggest to make more thorough processing of `train_percent_check` and `val_check_interval`:
1. We should require all `*_percent_check` and `val_check_interval` to be in the range [0.0; 1.0].
2. Final `num_val_batches` can be equal to `0` that will effectively disable validation.
3. Final `num_train_batches` and `num_test_batches` should be at least `1`. (See also #631)
4. Final `val_check_interval` should be at least 1.
5. The user can try to turn off validation by setting `val_check_interval` to a big value. Maybe in that case we should print a helpful message that validation can be turned off by setting `val_percent_check=0`.

Any thoughts?

**Comment by awaelchli** [comment]
I see. The max was introduced in a pull request that fixed an issue when `self.num_val_batches` was in the range (0, 1). One question, why should `*_percent_check` be in range [0, 1]. You mean [0, 100]? As the name suggests, it should be a percentage.

**Comment by kuynzereb** [comment]
Yeah, you are right, the naming is not correct. It is not real percents but just fractions. So now it is assumed that `1.` means to use the whole dataset.

**Comment by cmpute** [comment]
This behavior seems to be absent in the documentation?

**Comment by Borda** [comment]
@cmpute mind sending a PRs with docs?

**Comment by miccio-dk** [comment]
Sorry to exhume this old issue, but this feature doesn't seem to work any longer. These are my trainer arguments:
```
min_epochs: 1
max_epochs: 1
max_steps: 1000
num_sanity_val_steps: 0
overfit_batches: 1
log_every_n_steps: 1
val_percent_check: 0
```

I'm using this settings to completely avoid the validation dataset, and just overfit a single batch of data over 1000 training steps.

**Comment by ananthsub** [comment]
@miccio-dk this is a very old issue - I'd recommend creating a new one as the project has changed significantly since this was filed.

you may also be interested in this: https://github.com/PyTorchLightning/pytorch-lightning/issues/10888
