### ISSUE TITLE
pip install -e . crash

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#7]
Ran:  
```bash
pip install -e .
```    

Obtaining file:///Users/williamfalcon/Developer/opensource/pytorch-lightning
    Complete output from command python setup.py egg_info:
    error in pytorch-lightning setup command: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'pytorch-lightning=pytorch-lightning.cli:main')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/williamfalcon/Developer/opensource/pytorch-lightning/

@shreyasbapat

**Comment by shreyasbapat** [comment]
On it!

**Comment by shreyasbapat** [comment]
Please look at #8

**Comment by williamFalcon** [comment]
awesome!
