### ISSUE TITLE
change Checkpoint callback's `save_best_only` to `save_top_k`

### ISSUE THREAD

**Issue by vincentzlt** [williamFalcon/pytorch-lightning#70]
**Is your feature request related to a problem? Please describe.**
`save_best_only` is a special case of `save_top_k`. However, `save_tok_k` checkpoints can be used to create ensemble model during the test time.

**Describe the solution you'd like**
keep a dict of `{epoch: monitor}` of length `k`, and save new ckeckpoint that can enter this dict, remove the worst checkpoint.

**Comment by williamFalcon** [comment]
@vincentzlt good suggestion. I like the change.

Any takers? @vincentzlt interested in building this?

**Comment by Ir1d** [comment]
i'm interested in this feature, i'll give it a try :smile:

**Comment by williamFalcon** [comment]
awesome!

**Comment by Ir1d** [comment]
Hi, I have some questions.

I noticed `save_function` option was deleted in this commit: https://github.com/williamFalcon/pytorch-lightning/commit/63d84283a4cd91578c413b2ad6aaaec80e3fa3bc

But how does this line work then? https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/callbacks/pt_callbacks.py#L223-L224

Also, there were some `save_function=None` in docs, which make it somehow confusing.

**Comment by williamFalcon** [comment]
https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L137


https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/root_module/model_saving.py#L57

**Comment by williamFalcon** [comment]
@vincentzlt https://gitter.im/PyTorch-Lightning/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
