### ISSUE TITLE
Trainer.fit() crashes if no checkpoint callback is provided

### ISSUE THREAD

**Issue by egonuel** [williamFalcon/pytorch-lightning#72]
I hope it's okay that I keep posting issues...
Now that I can circumvent the github installation issues, I pulled in the latests master and let my simple CoolModel demo code run. But now calling trainer.fit() crashes with:

> AttributeError                            Traceback (most recent call last)
<ipython-input-3-4ff64ec6323b> in <module>
     21                  )
     22 
---> 23 trainer.fit(model)
     24 # exp.close()

> /opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/pytorch_lightning/models/trainer.py in fit(self, model)
    494                 self.optimizers, self.lr_schedulers = self.optimizers
    495 
--> 496             self.__run_pretrain_routine(model)
    497 
    498         # return 1 when finished

> /opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/pytorch_lightning/models/trainer.py in __run_pretrain_routine(self, model)
    680 
    681         # restore training and model before hpc call
--> 682         self.restore_state_if_existing_checkpoint()
    683 
    684         # enable cluster checkpointing

> /opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/pytorch_lightning/models/trainer.py in restore_state_if_existing_checkpoint(self)
    261 
    262         # find last epoch
--> 263         checkpoints = os.listdir(self.checkpoint_callback.filepath)
    264         for name in checkpoints:
    265             # ignore hpc ckpts

> AttributeError: 'NoneType' object has no attribute 'filepath'

Looking at the code, it appears to happen because I did not provide a checkpoint callback and it tries to access it in `restore_state_if_existing_checkpoint`

**Comment by egonuel** [comment]
now I added a ModelCheckpoint callback to test it and it still crashes, as the callbacks filepath does not exist when running for the first time

**Comment by williamFalcon** [comment]
good catch... definetely a bug from the thing i pushed yesterday.

there is no test for that particular case either haha. good catch!

**Comment by williamFalcon** [comment]
@egonuel try again. fixed

**Comment by egonuel** [comment]
@williamFalcon this also works now, thank you!
