### ISSUE TITLE
Update Lightning compatibility with PyTorch 1.2.0

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#79]
**Is your feature request related to a problem? Please describe.**
PyTorch 1.2.0 has breaking changes for the experiment object. 
Likely underlying changes to SummaryWriter.   

For now, Lightning requires pytorch 1.1.0 but need to update compatibility.

**Comment by williamFalcon** [comment]
@Borda apparently 1.2.0 came out a few hours ago which is breaking the summaryWriter... fixed the pytorch version for now to 1.1.0 unitl i sort that out

**Comment by cwerner** [comment]
Hm, I just downgraded torch to 1.1 but I still have problems with Experiment. I'm not getting any output for TensorBoard. Are there some more examples I could look at?

**Comment by williamFalcon** [comment]
you’re probably on a jupyter notebook. tensorbord and jupyter have issues

**Comment by cwerner** [comment]
I am indeed. Bummer... So no jupyterlab + TensorBoard for now?

**Comment by williamFalcon** [comment]
@cwerner yeah, maybe in this new version PT just released. update to 1.2.0 and lighting 0.4.2 to see what happens. they changed summaryWriter quite a bit

**Comment by cwerner** [comment]
Cool. Will do. Thanks 🙏

**Comment by Borda** [comment]
Sorry, I don't have connection now..

**Comment by cwerner** [comment]
@williamFalcon just a heads-up. Still no output in Lightning, but it get tb output if I use summarywriter directly in my PyTorch Code from jupyterlab (on Port 6006, not in the extension). Could be that I do miss something in the lightning code?!

**Comment by williamFalcon** [comment]
@cwerner ok, i need to look into  this bc Experiment IS a SummaryWriter as well.

Can you post code with both?

But at a minimum i can make it so SummaryWriter can just be used directly. That way we can start the process to support other loggers.

**Comment by cwerner** [comment]
Will be of my machine for a few days but will update and try. If I still have issues I’ll post some code here...
