### ISSUE TITLE
Dataset only available when the trainer is instantiated

### ISSUE THREAD

**Issue by LouisTrezzini** [williamFalcon/pytorch-lightning#86]
**Is your feature request related to a problem? Please describe.**
This is half feedback/feature request. Maybe our approach is not right be here is what we felt when trying this awesome library:

We would like to use a LightningModule in our pipelines, but we have some constraints which makes this difficult.

We have an experiment framework where we can register models (eg a LightningModule) by instantiating them. Then the framework trains the various model using some train/val/test data which is specified at runtime and generates performance reports.

Pseudo code:
```python
class TorchModel:
  def fit(x_train, y_train, x_val, y_val):
    trainer = Trainer(...)
    trainer.fit(self.module)

models = [
  ModelA(...),
  TorchModel(module=CoolModel()),  # TorchModel is actually a wrapper which exposes a common interface to Sklearn/Keras/Torch models
]

experiment_runner = Runner(models)
experiment_runner.run(train_dataset, val_dataset, test_dataset)
```

Or Uber's Ludwig would do:
```python
from ludwig.api import LudwigModel

# train a model
model_definition = {...}
model = LudwigModel(model_definition)
train_stats = model.train(training_dataframe)
```

**Describe the solution you'd like**
For us, the datasets / input tensors don't belong to the definition of the module. We understand that it improves reproducibility but it may reduce portability of models

They probably should be provided to the trainer at instantiation:
```
Trainer(train_dataset=..., val_dataset=...)

# And maybe
class CoolModel(pl.LightningModule):
    ...

    @pl.data_loader
    def tng_dataloader(self, dataset):
        return DataLoader(dataset, batch_size=32)

   ...
```
**Describe alternatives you've considered**
A temporary solution could be:
```
class TorchModel:
  def fit(x_train, y_train, x_val, y_val):
    self.module.set_train_dataset(x_train, y_train)
    self.module.set_val_dataset(x_val, y_val)
    trainer = Trainer(...)
    trainer.fit(self.module)
```

**Additional context**
Thanks for creating this library, this makes pytorch so much easier to use!

**Comment by williamFalcon** [comment]
@LouisTrezzini it sounds like your experimentation framework is just the trainer... if we made this change we'd end back up with scattered non-standard code. 

I'm not sure how portability would be affected? even if you did want to use your own trainer and feed your own data, then you'd probably just want to define a standard PyTorch module... CoolModel is just a nn.Module... nothing fancy about it.

But maybe I'm not understanding your use case.

**Comment by williamFalcon** [comment]
Probably one of the first things that happens in trainer is to get the dataset. so, your proposal is equivalent...

```python

**Current:**   
Class Trainer(...):
     def fit():
          load_datasets # one of the first things
```

**Proposed:**    

```python    
trainer(load_datasets())    
```    

Which is the same thing...

**Comment by LouisTrezzini** [comment]
Hello @williamFalcon, thanks for your prompt answer

> even if you did want to use your own trainer and feed your own data, then you'd probably just want to define a standard PyTorch module...

To reformulate, my use case would be to use your trainer and CoolModel's step methods, BUT with our own data / on multiple datasets.

How would you suggest we do this?
Thanks!

**Comment by williamFalcon** [comment]
@LouisTrezzini sure. just return your own dataloader instead of MNIST. If you need multiple aggregated datasets construct a joint dataloader (https://pytorch.org/docs/stable/data.html#torch.utils.data.ConcatDataset).    

Define your own data in:

```
@pl.data_loader
def tng_dataloader(self):
    # return your own dataloader or dataConcat
```   

Same for val and test data. [See the LightningModule  template](https://williamfalcon.github.io/pytorch-lightning/LightningModule/RequiredTrainerInterface/#minimal-example)

**Comment by williamFalcon** [comment]
@LouisTrezzini did this answer your questions? if so, we can close this issue
