### ISSUE TITLE
What should I do if I don't have validation data and test data?

### ISSUE THREAD

**Issue by illcat** [williamFalcon/pytorch-lightning#94]
```python
    @pl.data_loader
    def val_dataloader(self):
        # I don't need it.

    @pl.data_loader
    def test_dataloader(self):
        # I don't need it.

    def validation_step(self, batch, batch_nb):
         # I don't need it.

    def validation_end(self, outputs):
         # I don't need it.
```

**Comment by williamFalcon** [comment]
@illcat made optional in this upcoming PR #95. check back in a few hours and run from master

**Comment by williamFalcon** [comment]
install master branch and try again. val and test are optional

**Comment by illcat** [comment]
Sometimes I just want to load a trained model to predict  **unlabeled**  data. What should I do?
Is there no corresponding test method?

**Comment by illcat** [comment]
This means that trains and tests do not need to exist at the same time. One of them can work.

**Comment by williamFalcon** [comment]
@illcat. there is no test step yet but it’s alloted for this week. if you need it before you can load the model using the instructions in the docs and do your own test loop right now. otherwise, just check back in later in the week when it’s live.

**Comment by williamFalcon** [comment]
i don’t understand what you mean by trains are optional.
