### ISSUE TITLE
Old test_tube version

### ISSUE THREAD

**Issue by rcmalli** [williamFalcon/pytorch-lightning#99]
https://github.com/williamFalcon/pytorch-lightning/blob/46e27e38aae21227d0d0f1cab97ec10b8b8766c2/setup.py#L34

`test_tube` library version should be updated to `>=0.6.8`. This old version causes Tensorboard logging directory issues.

**Comment by williamFalcon** [comment]
good suggestion. feel free to make the PR. we’ll add it to the next release. in the meantime you can manually upgrade test-tube

**Comment by williamFalcon** [comment]
done on master
